### ISSUE TITLE
error "Buffer *temp* has no process"

### ISSUE THREAD

**Issue by non-Jedi** [dzop/emacs-jupyter#1]
Hi dzop,

I happened across this package, and it looked like a very promising and useful thing, so I've spent the past bit trying to get it to work. Initially I was running into a wall because `emacs-jupyter` isn't compatible with the head of master for `emacs-zmq`, but I've gotten that bit worked out by using an old commit for `emacs-zmq`, but the error I'm getting now is a bit beyond me, so I was wondering if you could point me in the right direction. It seems to be caused by the inner workings of your emacs zmq library and possibly multiple processes, and I have to admit it's a bit beyond me. Important-sounding lines from backtrace below (from calling `(jupyter-start-kernel "julia-1.0")`:

```emacs-lisp
Debugger entered--Lisp error: (zmq-subprocess-error void-function string-trim-right)
  signal(zmq-subprocess-error (void-function string-trim-right))
  zmq--subprocess-filter(#<process zmq> "(error void-function string-trim-right)")
  sleep-for(0.01)
  (while (null (process-get ioloop event)) (sleep-for 0.01))
```

```emacs-lisp
  jupyter-ioloop-wait-until(:start #<process zmq>)
```

```emacs-lisp
  jupyter--start-ioloop(#<jupyter-kernel-client jupyter-kernel-client>)
```

```emacs-lisp
  jupyter-start-channels(#<jupyter-kernel-client jupyter-kernel-client>)
```

```emacs-lisp
  jupyter-start-new-kernel("julia-1.0")
```

Appreciate any guidance you can offer.

**Comment by dzop** [comment]
Hi, I hadn't pushed any new commits in a while but I did just now. Could you pull in the new changes and maybe see if the problem is fixed. Let me know if it is still in issue.

**Comment by non-Jedi** [comment]
Still getting an error using latest master frpm both this repo and emacs-zmq (though completely different so that's progress).

```emacs-lisp
Debugger entered--Lisp error: (error "Buffer  *temp* has no process")
  process-send-region(nil 1 120)
  zmq-subprocess-send(nil (start-channel :shell "tcp://127.0.0.1:52208" "d43416b7-6cb4-4de4-aa48-26e0c92d31e5"))
...
  jupyter-start-channel(#<jupyter-shell-channel jupyter-shell-channel>)
...
  jupyter-start-channels(#<jupyter-kernel-client jupyter-kernel-client>)
...
  jupyter-start-new-kernel("julia-1.0")
```

I'm very excited about this if it works as stated in the README. Is this just something you've developed for your own personal use, or is there something more behind it? Thanks for making it available for others to use.

**Comment by non-Jedi** [comment]
This was caused by using the zmq library I specifically built with polling support with emacs while jupyter itself was using my system zmq installation. It seems to be working now, and I'm excited to try things out in it. :)

**Comment by dzop** [comment]
Glad to here. So you are saying `emacs-zmq` was using a `zmq` library without the polling support? I should probably have Jupyter raise an error if that is the case.

Regarding why I developed this:

It is a personal project. I decided to go ahead and give it a shot because I really like Jupyter, but I hate the notebook interface and most of what the notebook offers can be achieved with `org-mode` minus all of the Javascript. It also gave me an opportunity to learn how to use the `eieio` library in Emacs which I had been wanting to use for something. But first I had to write `emacs-zmq` since zmq is what Jupyter relies on for message passing. In that case it gave me an opportunity to write an Emacs C module.

**Comment by non-Jedi** [comment]
I ran into an error when running `make` for emacs-zmq which seems like it should be sufficient. And as for the specific problem I ran into, to be honest, my knowledge of how libraries work on linux in general and how libzmq works in particular is very very close to nonexistant. Here's the rough order of how things went down.

1. Installed `zeromq-devel` (pulls in zeromq library as well as headers)
2. Ran `make` in emacs-zmq and got the error about needing draft api.
3. Installed zeromq to `/usr/local/` with draft apis enabled.
4. Ran `ldconfig /usr/local/lib` and then `make`.
5. Got the error mentioned above about `"Buffer *temp* has no process"`.
6. Uninstalled system zeromq and system jupyter.
7. Installed jupyter via pip
8. Things work?

If it's helpful for you to make the library robust against this failure condition, I can try to recreate the non-working conditions and provide any debugging info needed... or I can just continue being content that I have a working system now. :)

**Comment by dzop** [comment]
Yeah if you could try to create the exact failure condition that would be great. I will also try with what you have here to see if I can find what happened. Thanks.

**Comment by non-Jedi** [comment]
What data would you like from me after I repro?

**Comment by dzop** [comment]
- In the `emacs-zmq` directory, the `src/config.log` file after running `make` in the top level directory after step 7 in your above comment and before step 5. The `Output variables.` section towards the end of the file should be good enough. Run `git clean -dfx` first before calling `make` so that the configure script doesn't attempt to use any cached values.
- Similarly, the output of the command `pkg-config --cflags --libs libzmq` in both cases.

**Comment by dzop** [comment]
@non-Jedi do you still bump into this issue? Maybe it can be closed seeing as the default behavior of `emacs-zmq` is to build a local copy of `libzmq` so most users won't need to go the route of using their own copy of `libzmq` with the error you mentioned?

Also the whole channel process machinery was updated shortly after you had this issue (see 6942a20e8a62629b4ab39c52596e35d2e0d1cda3) so hopefully the error is fixed.

**Comment by non-Jedi** [comment]
Sounds fine to me. I haven't ever tried to repro, but with the automatic building of libzmq, it doesn't seem likely to ever be a problem.
