### ISSUE TITLE
jupyter-repl-mode-map overrides C-n and C-p

### ISSUE THREAD

**Issue by alf-mindshift** [dzop/emacs-jupyter#100]
Please do not override C-n and C-p as that makes it much harder to copy paste text from the repl.

**Comment by dzop** [comment]
Can you explain why it would make copy pasting harder? Aren't the keybindings for the related operations on `C-w`, `C-y`, `M-y` (https://www.gnu.org/software/emacs/manual/html_node/emacs/Clipboard.html#Clipboard) or `C-x`, `C-c`, `C-v` if in CUA mode?

**Comment by alf** [comment]
Because I use C-n and C-p to navigate instead of arrow keys.

**Comment by dzop** [comment]
Oh yeah, I forgot those were the bindings for moving `point`. I use `evil-mode` so I'm not so familiar with the regular Emacs bindings. That's a pretty good reason to remove those bindings.

**Comment by alf** [comment]
Thank you, that was quick work!
