### ISSUE TITLE
Starting a repl attached to the kernel of the current org file

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-jupyter#109]
I was looking to implement a way to open a REPL while in an ORG file that uses the same kernel that the ORG file uses.

This way, I imagine one could run source blocks and then execute statements in a REPL that use variables/functions created in the source blocks.

I'd be happy to implement this and create a PR for it. However, I'm not sure if this is already possible. Some pointer would also be appreciated.

**Comment by dcherian** [comment]
I use `C-c C-v C-z` on a source block header line. This is the default org babel binding. I'm on a phone so I can't check what the actual command is

**Comment by UndeadKernel** [comment]
Ah, yes. That's what I was looking for.
In fact, it's also available from the Hydra in org-extensions.
