### ISSUE TITLE
Interrupting remote kernels

### ISSUE THREAD

**Issue by r-zip** [dzop/emacs-jupyter#110]
I've tried using this package with org-babel as a replacement for Jupyter notebooks with a remote notebook server. The only thing keeping me from switching entirely is the inability to interrupt the kernel if I make a mistake.

Is interrupting remote kernels truly impossible, or just difficult to implement? Without this ability, if you make a mistake, you have to lose all your state and start the session over from scratch. I don't think it will be possible to use this package for much other than small-scale experiments without remote kernel interruption.

**Comment by dzop** [comment]
Jupyter has an `interrupt_request` message type (https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-interrupt) that may be of use. The code is already there for interrupting a local kernel using this message type, but some work is needed to have ti work for remote kernels as well. Also I think the kernel itself needs to also support it, I'm not sure if all of them do.

Also I'm working on trying to support the notebook server in the future, more specifically the REST API the notebook server uses for communication. I'm starting with the Jupyter gateway first though, see https://github.com/dzop/emacs-jupyter/issues/74.

**Comment by dangom** [comment]
Would interrupting kernels be possible once the REST API is in place? Or otherwise, how much work would it be to get remote interrupts working (for someone without much experience with the codebase)? 

Did I understand correctly that only local kernels have a "kernel manager", and only kernels with a manager can be interrupted - and that is the issue?

**Comment by dzop** [comment]
> Would interrupting kernels be possible once the REST API is in place?

Yes if the kernel is started through the REST API, it will be possible to interrupt the kernel.

> only local kernels have a "kernel manager", and only kernels with a manager can be interrupted

Yes right now only kernels launched as local processes (in Emacs) or as remote processes via TRAMP have a kernel manager.

If you connect to a kernel using a JSON connection file, there is no manager, but even in this case it would still be possible to interrupt the kernel if it supports the `interrupt_request` message type. The code as it is written now has all of the interrupting logic in the kernel manager so there will need to be some code written to have the client send an `interrupt_request` if there is no manager associated with it and if the underlying kernel supports it. I don't think most kernels support this message type so it may not really be worth implementing.

There is probably a way to interrupt a remote kernel process started via TRAMP using `tramp-interrupt-process` though, that is if TRAMP uses an SSH session to start the kernel. This might already work.

**Comment by dzop** [comment]
The notebook REST API integration (#127) has been merged now so if your remote kernel is behind a notebook server you can connect to it and interrupt it as you would a local kernel. See the relevant sections about notebook servers in the README.
