### ISSUE TITLE
Kernel did not send startup message

### ISSUE THREAD

**Issue by Pfedj** [dzop/emacs-jupyter#111]
emacs 26.1
windows 10
configuration:
```
(add-to-list 'load-path "~/emacs-zmq/")  
(require 'zmq)

(add-to-list 'load-path "~/emacs-jupyter")
(require 'jupyter)

```
With eval
`M-: (setq jupyter--debug t) RET M-x jupyter-run-repl RET`
I get
```
Starting python3 kernel process...done
Kernel did not send startup message
Kernel starting up...done
SENDING: :kernel-info-request 47fefa1c-fae7-4867-bf75-a9d8646b9874 nil
SENT: (:shell 47fefa1c-fae7-4867-bf75-a9d8646b9874)
Requesting kernel info...done
```
On my other computer I have compiled emacs 27.050 with --with-modules option. Everything works well there (kernel starts and blocks are executed).

**Comment by dzop** [comment]
Can you try again on the latest master and if that doesn't work, maybe increase `jupyter-long-timeout`. There is also `jupyter-default-timeout`, but I think all of the startup stuff uses `jupyter-long-timeout`.

**Comment by Pfedj** [comment]
I have found the reason for the mistake. When executing i found the following message:
```
jupyter-start-kernel: Starting process with args "c:/msys64/usr/bin/python.exe -m 
ipykernel_launcher -f c:/Users/PC/AppData/Roaming/jupyter/runtime/emacs-kernel-ZX1Jpg.json"
SENDING: :kernel-info-request ec902f41-afde-4120-b424-cb4427be5533 nil
SENT: (:shell ec902f41-afde-4120-b424-cb4427be5533)
Requesting kernel info...done
```
 I changed in system PATH and put a line `C:\Anaconda3` above than `C:\msys64\usr\bin`. 
Now everything works. Thank you.
