### ISSUE TITLE
When results are silent, errors could be displayed using a popup

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-jupyter#12]
Currently, when setting the results to be silent (i.e., `:results silent`), tracebacks are displayed on the message buffer. An enhancement would be to display these errors in a popup buffer using emacs' `pop-to-buffer`. This would enable, among other desired effects, to follow the link to the error printed as `[goto error]`.

**Comment by dzop** [comment]
This a good idea. It is weird that the `[goto error]` string is shown in the message buffer since it doesn't work there.
