### ISSUE TITLE
org-src-lang-modes of jupyter-C++ and jupyter-R are not worked.

### ISSUE THREAD

**Issue by hwiorn** [dzop/emacs-jupyter#122]
emacs-jupyter version: 20190523.1349

When opening an any org file, an unsupported mode(actually uppercase character) is added. 
Maybe there is no downcase function there. but i found [this changes](https://github.com/dzop/emacs-jupyter/blob/master/ob-jupyter.el#L475) and commit #107 .
Can you check this out?

#### Procedure
Start emacs and check the `org-src-lang-modes` value.

~~~
Value:
(("jupyter-C++17" . c++)
 ("jupyter-C++11" . c++)
 ("jupyter-C++14" . c++)
 ("jupyter-R" . r)
 ("jupyter-python" . python)
 ("ipython" . python)
 ("dot" . graphviz-dot)
 ("arduino" . arduino)
 ("translate" . text)
 ("redis" . redis)
 ("php" . php)
 ("C" . c)
 ("C++" . c++)
 ("asymptote" . asy)
 ("bash" . sh)
 ("beamer" . latex)
 ("calc" . fundamental)
 ("cpp" . c++)
 ("ditaa" . artist)
 ("elisp" . emacs-lisp)
 ("ocaml" . tuareg)
 ("screen" . shell-script)
 ("shell" . sh)
 ("sqlite" . sql))
~~~

Then open the any org file and check the `org-src-lang-modes` value

~~~
Value:
(("jupyter-C++17" . C++)
 ("jupyter-C++11" . C++)
 ("jupyter-C++14" . C++)
 ("jupyter-R" . R)
 ("jupyter-C++17" . c++)
 ("jupyter-C++11" . c++)
 ("jupyter-C++14" . c++)
 ("jupyter-R" . r)
 ("jupyter-python" . python)
 ("ipython" . python)
 ("dot" . graphviz-dot)
 ("arduino" . arduino)
 ("translate" . text)
 ("redis" . redis)
 ("php" . php)
 ("C" . c)
 ("C++" . c++)
 ("asymptote" . asy)
 ("bash" . sh)
 ("beamer" . latex)
 ("calc" . fundamental)
 ("cpp" . c++)
 ("ditaa" . artist)
 ("elisp" . emacs-lisp)
 ("ocaml" . tuareg)
 ("screen" . shell-script)
 ("shell" . sh)
 ("sqlite" . sql))
~~~

**Comment by dzop** [comment]
`org-src-lang-modes` is modified only in that one place so I'm thinking this issue is related to your personal configuration. Can you open a fresh Emacs, run the following code, open an `org-mode` file, and show the backtraces that are printed to `*Messages*`

```emacs-lisp
(defun my/org-src-lang-modes-watcher (_symbol _newval op _where)
  (when (eq op 'set)
    (backtrace)))

(add-variable-watcher 'org-src-lang-modes 'my/org-src-lang-modes-watcher)
```

You can then remove the variable watcher using

```emacs-lisp
(remove-variable-watcher 'org-src-lang-modes 'my/org-src-lang-modes-watcher)
```

**Comment by hwiorn** [comment]
Your code was helpful in tracking down the problem.

Root cause was `ob-ipython`. I am using `Spacemacs` and `ipython-notebook` layer. Actually i thought `ob-ipython` was not installed. But `ipython-notebook` layer requires `ob-ipython` in develop branch.

Thank you! It was helpful!
