### ISSUE TITLE
Segmentation fault (core dumped), (help with installing)

### ISSUE THREAD

**Issue by Xparx** [dzop/emacs-jupyter#128]
I manage to install emacs-jupyter following the instructions on one of my machines without much fuss. Works great!

(Probably an issue with emacs-zmq but i'll post here if you guys might have a solution for me)

However now I try to do the same on my work machine and after trying to `M-x package-install RET jupyter` i get a `Segmentation fault (core dumped)` Message
`M-x emacs-version` gives `GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-06-08`.

When I get the option to `Check compatible module binary to download` picking yes crashes emacs. Picking no starts the compilation proceedure with asking if zmq should be built. This process continues for a while before it crashes emacs.

After some trial and error it seems to be an issue with emacs-zmq. I'll see if I can get an answer from there. Trying to clone compile an test emacs-zmq result in core dumped so I have to assume it's where the problem is https://github.com/dzop/emacs-zmq/issues/14.

Any help is appreciated though.

**Comment by Rizzey** [comment]
Not sure if it'll help much, its a ridiculous workaround, but I had the same issue a few days ago trying to `M-x package-install RET emacs-jupyter`.
I seemed to have this problem trying to run it on emacs 27 - depending on where you got it from it may not have been compiled with the --with-modules flag. Either that or theres some kind of weird interaction going on between emacs 27 and emacs-jupyter.
I solved the problem by... capitulating and installing a version of emacs 26.1 that had been compiled with module support. I don't know much about this stuff but I hope a simple "hey I had this bug too" helps slightly.

**Comment by Xparx** [comment]
@Rizzey thanks for the advice. I'll see if that is a good solution for me. I can survive without emacs-jupyter for now as i'm trying to move away from ob-ipython i am still using it.

It looks like there is some issue with the optimization flags when compiling if you take a look at the link I posted above.  How did you get hold of an older emacs version? Do you compile yourself or do you have access to a deb file (I'm on Ubuntu)?

**Comment by dzop** [comment]
@Rizzey Do you know what kinds of errors you were getting when trying `emacs-jupyter` on Emacs 27? I ran the test suite on Emacs 27 recently (https://travis-ci.com/dzop/emacs-jupyter/jobs/221063031) and, although the tests fail, the failures wouldn't really cause problems under normal usage.

I'm closing this issue since the original problem has already been found and is discussed in more detail in https://github.com/dzop/emacs-zmq/issues/14. If there are indeed issues when trying `emacs-jupyter` in Emacs 27 please open up a new issue.
