### ISSUE TITLE
progn: Symbol's function definition is void: when-let

### ISSUE THREAD

**Issue by cheremin** [dzop/emacs-jupyter#133]
I've got those errors in last version (20190613) while evaluating orgmode scriptlets. It appears constantly, after each try to evaluate. I'm not sure is it due to new version, but it seems likely.

**Comment by dzop** [comment]
Are you using compiled versions of the source code? If you evaluate `(require 'subr-x)` and the problem goes away it is most likely because the compiled versions of the sources are not being used.

**Comment by cheremin** [comment]
Well, I've installed package from melpa, with `(use-package jupyter :ensure t)` -- i.e. I don't know are there compiled versions. But I've tried `(require 'subr-x)` after fresh emacs restart, and indeed,  `Symbol's function definition is void` goes away. (I've noted same does happen if I run `jupyter-run-repl`)

But new problem appears instead: now block of code is executed, but results are just GUID:
`: 1 - 39e2567f-faec-46b6-a731-893b969222ec`
and minibuffer state `error in process sentinel: save-current-buffer: Search failed: "b5d6bfb3-e37f-4c58-a2e5-edcf1ad2430f"`
I've noted, GUIDs in document and in error message are off by one: i.e. next time I try to run same block I'll get error about not being able to find "39e2567f-faec-46b6-a731-893b969222ec", while this ID in document are already replaced with the next one.

**Comment by cheremin** [comment]
Ok, seems like I've solved 2-nd issue: looks like `ob-ipython` which I have installed and used before, somehow conflicts with `emacs-jupyter`. I'm not so familiar with emacs debugging to got all the details, but the result processing for `jupyter-python` source block is somehow go through `ob-ipython` code.

**Comment by dzop** [comment]
It would be a good idea to add some note in the documentation about incompatibility with `ob-ipython` I think someone has had a similar issue in the past. Would you like to make a note in the documentation, under the `=org-mode= source blocks` section, and submit a pull request?

**Comment by cheremin** [comment]
> It would be a good idea to add some note in the documentation about incompatibility with `ob-ipython` I think someone has had a similar issue in the past. Would you like to make a note in the documentation, under the `=org-mode= source blocks` section, and submit a pull request?

Sorry for a delay
Yes, sure, here is my version: https://github.com/dzop/emacs-jupyter/pull/135
