### ISSUE TITLE
Emacs-jupyter doesn't catch :session from orgmode header-args without explicit language

### ISSUE THREAD

**Issue by cheremin** [dzop/emacs-jupyter#136]
It is quite noisy to set `:session` in each source block in org-file: usually, all blocks in file are naturally belong to same session. I've tried to use per-file property set, and per-language construct does work:
```
#+PROPERTY: header-args:jupyter-python :session my-session
```
while "any language" construct -- doesn't:
```
#+PROPERTY: header-args :session my-session
```
(jupyter claims `Need a session to run`). 

While really first option is enough, it would be useful for 2-nd one to also work: e.g. it is easier to have language-agnostic orgmode template with `header-args :session <filename>`, and don't worry about specific language I'll be using this time.

**Comment by dzop** [comment]
I'm not seeing this behavior on Org 9.2.2, the `header-args` property gets recognized. `emacs-jupyter` gets all of the source block information from `org-mode` itself so if the property isn't being recognized that would be an `org-mode` issue.

Did you press `C-c C-c` on the `#+PROPERTY` line? When you add a new `#+PROPERTY` line (or modify an existing one) within an already opened `org-mode` file you have to press `C-c C-c` on the `#+PROPERTY` line to refresh the local file properties.

**Comment by cheremin** [comment]
>I'm not seeing this behavior on Org 9.2.2, the header-args property gets recognized. 

Indeed, my org was v9.1+, and after upgrade issue was gone. 

Thank you!
