### ISSUE TITLE
No content displayed in the browser when a widget output is produced

### ISSUE THREAD

**Issue by Yevgnen** [dzop/emacs-jupyter#142]
The javascript build is success. When I test something like `from ipyleaflet import *`, a blank page of the browser is open but with errors displayed in the console

<img width="1440" alt="Screen Shot 2019-07-10 at 7 50 55 PM" src="https://user-images.githubusercontent.com/16749790/60967174-968a5180-a34c-11e9-88d2-02395f4586cb.png">

How can I debug this? Thanks!

**Comment by dzop** [comment]
I don't think anything significant has changed in the code that would cause problems with all of the widget stuff, but unfortunately I haven't looked at it in a while. If you evaluate `(setq jupyter--debug t)` and try again can you show the messages printed in the `*Messages*` buffer.

Also how are you connecting to the kernel? Is this a kernel that you started through Emacs, e.g. using `jupyter-run-repl` or are you connecting to an already existing kernel? If the latter how did you start the kernel?

**Comment by dzop** [comment]
Looking over the code briefly I did find an issue that I fixed in 08a4723c0b72e7736a1fe4c099beb175d54a0394. If you update `emacs-jupyter` to the latest version (probably be an hour or so before its on MELPA) it may fix your problems.

**Comment by Yevgnen** [comment]
Hi, thanks for the quick reply.

I originally test the widget feature in org babel, with the kernel start automatically. Seeing that it didn't work, I use `jupyter-run-repl` to start the kernel manually (`M-x` jupyter-ru-repl` -> `Python 3`) but the error is the same.

The latest version seems work for me.  

<img width="1440" alt="Screen Shot 2019-07-11 at 8 18 21 AM" src="https://user-images.githubusercontent.com/16749790/61013445-1cda7e00-a3b5-11e9-8270-96fdeca1eba9.png">


May I ask one more off topic question? How can I interrupt a long run evaluation when I'm using in `org-babel` with `:async` execution? 

Thank you!

**Comment by dzop** [comment]
> How can I interrupt a long run evaluation when I'm using in org-babel with :async execution?

You should be able to press `C-c C-i` when `point` is inside any source block connected to the kernel.

**Comment by Yevgnen** [comment]
Thanks!
