### ISSUE TITLE
`list-processes` failed after connected to a kernel

### ISSUE THREAD

**Issue by Yevgnen** [dzop/emacs-jupyter#145]
After a `emacs-jupyter` connect to a kernel, `list-processes` raises

    Debugger entered--Lisp error: (wrong-type-argument sequencep t)
      mapconcat(identity t " ")
      list-processes--refresh()
      list-processes()
      funcall-interactively(list-processes)
      call-interactively(list-processes nil nil)
      command-execute(list-processes)

Reproduce steps:

1. Open a `org` file and enter a `jupyter-python` block.
2. Press `C-c C-c` to eval the block.
3. Run `M-x list-processes`

Sample test config:

    (package-initialize)

    (require 'org)
    (setq org-confirm-babel-evaluate nil)
    (require 'jupyter)

    (org-babel-do-load-languages 'org-babel-load-languages
                                 '((emacs-lisp . t)
                                   (python . t)
                                   (shell . t)
                                   (latex . t)
                                   (jupyter . t)))

**Comment by dzop** [comment]
This is a known problem, there is a patch that you can apply in https://github.com/dzop/emacs-jupyter/issues/98#issuecomment-486414019.

It has to do with `list-processes--refresh` not handling the `t` value that can be returned by `process-command` for pipe processes. Those kinds of processes are used for the `stderr` streams of subprocesses that we start, but they are really only used for debugging purposes.

**Comment by dzop** [comment]
There isn't anything we can do about this on the `emacs-jupyter` side. So closing.
