### ISSUE TITLE
Spacemacs layer and adding to melpa?

### ISSUE THREAD

**Issue by benneti** [dzop/emacs-jupyter#15]
Hey,
I tried to write a spacemacs layer for this package (which on my main machine does work as intended but on my main machine the installation of the package from github fails for some reason not obvious to me).
This would be way easier if the package was on melpa, so do you plan on releasing it there?
If you are not to familiar with spacemacs the package installation is just done via quelpa which in turn fails to get the package-desc.

Thanks for the package, I think it will be a great addition to combine emacs with jupyter using this.

```
;;; packages.el --- emacs-jupyter layer packages file for Spacemacs.
;;
;; Copyright (c) 2012-2018 Sylvain Benner & Contributors
;;
;; Author: Benedikt Tissot <benneti@bennetis-xps>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;;; Commentary:

;; See the Spacemacs documentation and FAQs for instructions on how to implement
;; a new layer:
;;
;;   SPC h SPC layers RET
;;
;;
;; Briefly, each package to be installed or configured by this layer should be
;; added to `emacs-jupyter-packages'. Then, for each package PACKAGE:
;;
;; - If PACKAGE is not referenced by any other Spacemacs layer, define a
;;   function `emacs-jupyter/init-PACKAGE' to load and initialize the package.

;; - Otherwise, PACKAGE is already referenced by another Spacemacs layer, so
;;   define the functions `emacs-jupyter/pre-init-PACKAGE' and/or
;;   `emacs-jupyter/post-init-PACKAGE' to customize the package as it is loaded.

;;; Code:

(defconst emacs-jupyter-packages
  '(zmq
    simple-httpd
    websocket
    (emacs-jupyter :location (recipe
                              :fetcher github
                              :repo "dzop/emacs-jupyter"))))

(defun emacs-jupyter/init-zmq ()
  (use-package zmq
    :defer t
    :ensure nil))

(defun emacs-jupyter/init-simple-httpd ()
  (use-package simple-httpd
    :defer t
    :ensure nil))

(defun emacs-jupyter/init-websocket ()
  (use-package websocket
    :defer t
    :ensure nil))

(defun emacs-jupyter/init-emacs-jupyter ()
  (use-package emacs-jupyter
    :defer t
    :ensure nil
    :after '(emacs-zmq websocket simple-httpd)))

;;; packages.el ends here
```

**Comment by benneti** [comment]
that's good to kno,  thanks.
@vv111y I think as soon as all the packages are in the melpa doing a pull request for spacemacs is more appropriate.
So I will wait until then. 
(Also thanks for the info with the http layer, the layer was just a naive try where I did not look for anything as I just wanted to try out the package)
Do you want to start working on a layer non the less?
Then I could create a repo for it already integrating it in another layer should not be too hard and in my opinion this would deserve its own layer as neither the Python (it works as good for julia and other languages) nor the ipython-notebook (I was really surprised that ob-ipython was in there) layer seem to fit completly

**Comment by benneti** [comment]
Here is the [repo](https://github.com/benneti/spacemacs-jupyter), currently it does not have keybindings and your hint was not considered either.

**Comment by dzop** [comment]
See melpa/melpa#6009
