### ISSUE TITLE
Output from source code called with #+CALL is not shown

### ISSUE THREAD

**Issue by hilman-dayo** [dzop/emacs-jupyter#154]
Hey.
Thank for the great library!

However, it seems that there are problems with the output produced from `jupyter-python` when the code blocks are called through  `#+CALL`.

For example, if I tried to save a plot through `:file`, it cannot detect it and instead, it will save it in an `.ob-jupyter` directory.
It also cannot output simple print results from the code block.

Below is the screenshot of the problems:
![jupyter-tanya](https://user-images.githubusercontent.com/16521877/61855718-90bf6f00-aefb-11e9-9a22-a1abf9eedc33.png)

This is weird because I am positive that there were no problems like this before.
Thanks!

**Comment by dzop** [comment]
Thanks, should be fixed now.
