### ISSUE TITLE
tramp-error: Not a Tramp file name

### ISSUE THREAD

**Issue by Yevgnen** [dzop/emacs-jupyter#155]
When `(setq org-src-tab-acts-natively t)`, this error happens. Test config:

```elisp
;; -*- lexical-binding: t; -*-

(require 'package)

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))

(package-initialize)
(setq package-enable-at-startup nil)

(setq org-src-tab-acts-natively t)

(require 'jupyter)
(org-babel-do-load-languages 'org-babel-load-languages
                             '((emacs-lisp . t)
                               (python . t)
                               (shell . t)
                               (latex . t)
                               (jupyter . t)))

```

Test file: 

```
#+property: header-args:jupyter-python :session test :async yes :exports both :tangle test.py

#+begin_src jupyter-python
import pandas as pd
#+end_src
```

Reproduce: Open a `org` file, then place the cursor in a `jupyter-python` block, press `TAB`. 

Enabling debug mode of `tramp` or `jupyter` or `toggle-debug-on-error` outputs nothing more messages.

- Emacs version: `GNU Emacs 26.2.90 (build 1, x86_64-apple-darwin18.6.0, Carbon Version 158 AppKit 1671.5) of 2019-06-19`

- Org mode: `Org mode version 9.2.4 (9.2.4-11-g1c3eae-elpaplus @ /Users/user/.emacs.d/elpa/org-plus-contrib-20190722/)`

**Comment by dzop** [comment]
Thanks I can confirm this will look into it.

**Comment by Yevgnen** [comment]
Thanks for the quick fix.
