### ISSUE TITLE
Associating local files to remote kernels?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#156]
I noticed that it doesn't seem to be possible to associate files to remote kernels. Is that a hard restriction by design, or just a use-case that hasn't come up yet?

I started a kernel on remote and connect to it via
```
#+property: header-args:jupyter-python :session /ssh:remote:~/kernels/remote.json
```

When I then try to `jupyter-repl-associate-buffer`, I get a message that no REPL exists for major-mode, and whether I'd like to start one.

I think remote development with local files would be a really powerful feature to have for the development of small projects or quick scripts.

**Comment by dangom** [comment]
Actually, that does work. I was hitting #141 again and when the kernel is *apparently* not alive, the associate-buffer functionality does not allow connecting to it.

**Comment by dzop** [comment]
Were you able to do what I mentioned in https://github.com/dzop/emacs-jupyter/issues/141#issuecomment-508206425 to see if it changes the situation?

**Comment by dangom** [comment]
Giving it a try. The issue is not consistent, so I'll give it a week with the changes suggested in #141 and see if it disappears.

**Comment by dangom** [comment]
I'll close this one since it's a duplicate.
