### ISSUE TITLE
Output of long arrays wrapped in "example"-block and duplicated for each evaluation of the source block

### ISSUE THREAD

**Issue by Aquan1412** [dzop/emacs-jupyter#157]
Hello, I noticed that the contents of long arrays get wrapped in an "example"-block by jupyter-python. That wouldn't be problem, however, those blocks don't get updated when I repeatedly evaluate the block. Instead, new example-blocks are added, cluttering the whole file. 

As an example: for a short array, i get the following result:

> #+BEGIN_SRC jupyter-python  :session test :results drawer
import numpy as np
np.random.rand(25)
#+END_SRC

> #+RESULTS:
: array([0.57265889, 0.88313146, 0.47686844, 0.32759135, 0.83877408,
:        0.67215053, 0.42809974, 0.80967376, 0.80489529, 0.96541111,
:        0.81495484, 0.00280137, 0.43826718, 0.54021045, 0.67173431,
:        0.5073497 , 0.57104896, 0.73877455, 0.41250193, 0.21627113,
:        0.93024327, 0.07405166, 0.45374239, 0.74379152, 0.61381835])

When I re-evaluate the source block, the "Results" section is simply updated, as I would expect it.

However, for a longer array, output changes to the following:

> #+BEGIN_SRC jupyter-python  :session test :results drawer
import numpy as np
np.random.rand(51)
#+END_SRC

> #+RESULTS:
#+begin_example
array([0.92593732, 0.16298991, 0.54099657, 0.28499497, 0.85593837,
       0.9185376 , 0.57928991, 0.91668272, 0.9380359 , 0.65341115,
       0.26711604, 0.8680568 , 0.50898124, 0.42938046, 0.01676723,
       0.78074776, 0.41949106, 0.74462307, 0.67153754, 0.76379976,
       0.26178625, 0.82661089, 0.43692498, 0.47462707, 0.64783823,
       0.71866072, 0.90222347, 0.54867071, 0.07991856, 0.87574953,
       0.66436081, 0.27867879, 0.39362728, 0.3572362 , 0.42711561,
       0.53753667, 0.00241583, 0.90190677, 0.29681949, 0.70797795,
       0.65244512, 0.28449106, 0.30470306, 0.09111712, 0.63902914,
       0.51537505, 0.46140844, 0.46104142, 0.26309854, 0.41759003,
       0.76617175])
#+end_example
#+begin_example
array([0.85363123, 0.8049987 , 0.34975436, 0.3302924 , 0.87000055,
       0.59204195, 0.43787697, 0.19909464, 0.09001819, 0.13925253,
       0.78721872, 0.50008234, 0.36918045, 0.86583919, 0.8351256 ,
       0.9055147 , 0.16816715, 0.99905522, 0.89240604, 0.49863127,
       0.99651494, 0.4255257 , 0.95090911, 0.33229878, 0.44281194,
       0.85085189, 0.82885678, 0.57821344, 0.45247358, 0.91503098,
       0.99507702, 0.9350082 , 0.32820534, 0.4132617 , 0.23270099,
       0.84018169, 0.69911898, 0.90011571, 0.19294698, 0.74040744,
       0.54894151, 0.09471358, 0.93826788, 0.80931011, 0.75546161,
       0.2201491 , 0.0334262 , 0.87558507, 0.06355036, 0.11335044,
       0.49054737])
#+end_example

For each re-evaluation of the source block, a new example block gets added...
Is the wrapping of results in an example block intentional? And if so, can it be changed, so that the content of the example block is updated, instead of creating a completly new block?

**Comment by dzop** [comment]
Yes the wrapping of the example block is intentional, see `org-babel-min-lines-for-block-output` although we use it also for the result of a code block.

Do you have ob-ipython installed? What is your org-mode version? And how did you install emacs-jupyter, if you installed it from source what is the commit number, if from MELPA what is the MELPA version?

I do not get this behavior on Org 9.2.2 and the current master version of emacs-jupyter. The example block is updated not duplicated.

**Comment by Aquan1412** [comment]
I installed emacs-jupyter via MELPA. The MELPA version is 20190725.848
My org-mode version is 9.2.4

Concerning ob-ipython: is used to have it installed until maybe a month ago, then I uninstalled it, since I completely switched to emacs-jupyter.

**Comment by dzop** [comment]
I'm not able to reproduce from an `emacs -Q` session. Can you evaluate the following in your current Emacs session

```emacs-lisp
(with-temp-file "issue-157.el"
  (dolist (pkg '("websocket" "simple-httpd" "zmq" "jupyter" "org"))
    (insert (format "(push \"%s\" load-path)\n" (file-name-directory (locate-library pkg)))))
  (insert "\
\(require 'org)
\(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (jupyter . t)))
\(pop-to-buffer (get-buffer-create \"test-buffer\"))
\(org-mode)
\(insert \"\
#+begin_src jupyter-python :session test
import numpy as np
np.random.rand(51)
#+end_src
\")
\(org-babel-previous-src-block)
"))
```

And from a terminal where the `issue-157.el` file was written to, call the shell command 
`emacs -Q -l issue-157.el`. I did this after I upgraded to Org 9.2.4 and was unable to reproduce the problem. If you are also unable to reproduce it from an `emacs -Q` session then there may be something interaction with how Org is set up in your personal config. Are you using spacemacs or similar?

**Comment by Aquan1412** [comment]
I did as you asked, and in this clean environment the example block gets updated, as it should be. I'm not using spacemacs or something similar, just normal emacs with plenty of customization. If I have some time in the next days I'll go through my org setup to see if I can find the reason for my problem. Thank you for your help!

**Comment by Aquan1412** [comment]
OK, I found the problem. Actually, it's not even related to org. I was using some functions from the scimax project for org babel. One of those, scimax-execute-and-next-block, evaluates the current source block and creates a new source block below with the same header information etc. When I use that to evaluate the source block (which was my default), the described problem appears. When I evaluate the block the conventional way, the results get updated as they should.
