### ISSUE TITLE
Auto-start remote kernel not working

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#162]
Currently my workflow has consisted of calling `python -m ipykernel_launcher -f ~/remote.json` on a remote computer, and then connecting to ia via an Org block specifying `:session /ssh:remote:~/remote.json`.

I've tried a couple of times emacs-jupyter auto-spawn feature, but never really got it to work. I think it's probably an issue at my end, but if someone has a hint, I'd appreciate it.

When I do `:session /ssh:remote:test`, I get an error saying `(error "Can’t obtain kernelspecs from jupyter shell command")`. 
My tramp config has  `(add-to-list 'tramp-remote-path 'tramp-own-remote-path)`, but that doesn't seem to make a difference.
Is there something I have to do on the remote side in order for jupyter to find the `jupyter` command? In my `.bashrc` or `.zshrc` I initialize conda via the conda provided initialize setup.

**Comment by dzop** [comment]
What does the following return?

```emacs-lisp
(let ((default-directory "/ssh:remote:"))
  (with-temp-buffer
    (process-file "jupyter" nil t nil "kernelspec" "list")
    (buffer-string)))
```

This is probably another case where better logging would reveal the problem.

**Comment by dangom** [comment]
Yes, seems like jupyter is not found. =/
I don't have admin rights on these remote machines, so I can't symlink jupyter in /usr/local, unfortunately.

```org
#+begin_src emacs-lisp
(let ((default-directory "/ssh:remote:"))
  (with-temp-buffer
    (process-file "jupyter" nil t nil "kernelspec" "list")
    (buffer-string)))
#+end_src

#+RESULTS:
: sh: jupyter: command not found
```

**Comment by dzop** [comment]
Maybe add the `conda` stuff in `~/.profile` on the remote. It seems TRAMP is using `sh` on the remote so the `bash` specific setup in `~/.bashrc` is most likely not being loaded. 

Alternatively you could probably modify the `tramp-remote-shell` variable in the `ssh` method of `tramp-methods` to use `bash`.

**Comment by dangom** [comment]
Solved.
Had to look into [this SO answer about setting PATHs for sh & tramp](https://stackoverflow.com/a/10464554/3568092) to get it to work correctly.

Thanks!!

**Comment by dangom** [comment]
There is still an edge case where it doesn't seem to work if I double hop via a ProxyJump (in ssh config).
This works :session `/ssh:remote:test`, this too`/ssh:entry|ssh:remote:test`, but this doesn't: `/ssh:remote-tunnel:test`. The kernel doesn't seem to respond to kernel-info request.

```
# ssh config
Host remote-tunnel
     User user
     ProxyJump entry
     HostName remote
```
