### ISSUE TITLE
Error specializing jupyter-repl-after-init

### ISSUE THREAD

**Issue by r-zip** [dzop/emacs-jupyter#166]
I've got a bit of custom code to automatically set the current working directory and virtual environments for projects when opening shells and REPLs. To use this code with `emacs-jupyter`, I tried using the `jupyter-send-execute-request` function via both `jupyter-repl-mode-hook` and `jupyter-repl-after-init`. In both cases, the code executes successfully, but I get the following error in the message buffer:

```
Error running timer ‘jupyter-event-handler’: (error "Cell for request not found")
```

The code I am executing is

```elisp
(cl-defmethod jupyter-repl-after-init (&context (jupyter-lang python))
  (-when-let (proj-info (r-zip/get-pyproject-info))
    (jupyter-send-execute-request
        jupyter-current-client
      :code (pyproject-cd-project-root-command proj-info)
      :silent t)))
```
where the `r-zip/`-prefixed items are defined in my init. Am I doing something obviously wrong? Do I need to set up some request handler or callback to avoid getting this error message?

**Comment by dzop** [comment]
You want to wrap the execute request like

```emacs-lisp
(let ((jupyter-inhibit-handlers t))
  (jupyter-send-execute-request
      jupyter-current-client
    :code (pyproject-cd-project-root-command proj-info)
    :silent t))
```

so that the handler methods that update the REPL state don't get evaluated.

**Comment by r-zip** [comment]
Thanks for the prompt reply! Works like a charm.
