### ISSUE TITLE
jupyter-org-extensions breaks the work of major-mode-hydra for org-mode

### ISSUE THREAD

**Issue by Pfedj** [dzop/emacs-jupyter#169]
I would like to use package [major-mode-hydra](https://github.com/jerrypnz/major-mode-hydra.el) for settings hydra key binding for org-mode.
This is my settings:
```
(use-package major-mode-hydra
  :ensure t
  :bind
  ("M-SPC" . major-mode-hydra))

(major-mode-hydra-define org-mode nil
  ("Emacs"
   (("<escape>" nil "quit")
    ("q" nil "quit"))))
```
I have found that adding this line in my init file breakes the work of this package:
```
(require 'jupyter-org-extensions)
```
How can I fixed it?

**Comment by dzop** [comment]
> breaks the work of this package

What specifically breaks, e.g. what errors or keybindings that don't work?

Calling `(require 'jupyter-org-extensions)` doesn't actually create the Jupyter hydra. It will be created on the first press of `C-c h` in an `org-mode` buffer. All that loading `jupyter-org-extensions` does (related to the hydra) is add the `C-c h` binding to `jupyter-org-interaction-mode-map`.

**Comment by Pfedj** [comment]
> What specifically breaks, e.g. what errors or keybindings that don't work?
Unusually I press ```M-<SPC>``` and pop up menu with the hints. In this case this does not happen. I see just typing ```M``` and ```SPC``` in emacs output stream.
Also I plunged deeper and found that the reason for that in the following line in the file ```jupyter-org-client.el```:
```(add-hook 'org-mode-hook 'jupyter-org-interaction-mode)```
when it is connented, hints work.

**Comment by dzop** [comment]
I'm not so sure this is related to emacs-jupyter. There are no default keybindings bound to `M-SPC` that emacs-jupyter sets so I don't see how your `M-SPC` binding works or doesn't depending on if `jupyter-org-interaction-mode` is enabled or not.

Also I looked at the major-mode-hydra code and it is very simple. There is nothing obvious there that would interact badly with anything that emacs-jupyter does. All it does is call a hydra function based on the `major-mode`. For example if you are in `org-mode`, it just evaluates 

`(call-interactively #'major-mode-hydras/org-mode/body)`

Where `major-mode-hydras/org-mode/body` is just the function created by a call to `defhydra`.

I would suggest you try to reproduce the problem with a minimal `init.el` file that just loads emacs-jupyter and major-mode-hydra. If you are able to reproduce, can you post the `init.el` file here and the steps necessary for the reproduction.

**Comment by Pfedj** [comment]
I have found the mistake. I had the following lines at the top in myinit file:
```
(general-define-key
 :keymaps 'jupyter-org-interaction-mode-map
 :prefix "M-<SPC>"
            (kbd "cc") 'org-ctrl-c-ctrl-c)
```
I had doubts in regards that it wotked before call ```(require 'jupyter-org-extensions)```. 
Thank you for your clarification.
