### ISSUE TITLE
Import error - no module named "jupyter_client"

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#170]
Earlier today, in the remote I work on, I had to delete my anaconda install in my home directory and install it somewhere else because of quota issues. Since then I'm having some problems getting emacs-jupyter to work on said remote. Every time I try to connect I get a "import error: no module named 'jupyter_client'".

I'm 100% positive the module is installed, and calling `M-x shell` with a remote default directory, I see that the PATH is also correct.

Has anyone come across this issue before? I'd be happy to hear about some sanity checks I could run, maybe I'm missing something obvious.

**Comment by dangom** [comment]
I still don't know what was going on, but there was some inconsistency in my conda environment
> The environment is inconsistent, please check the package plan carefully

It's a bit weird because I installed anaconda the way I always did before, but it seems that there are issues with python 3.7.4 were pip installing some packages lead to [some dependencies not building properly](https://github.com/tensorflow/tensorflow/issues/31523).

My solution was to downgrade to python 3.7.3 and reinstall jupyter.

**Comment by dangirsh** [comment]
In case someone else wanders here:

This happened to me today on a remote machine that had jupyter installed in a user-level conda base environment , but not the root environment. I saw that the `jupyter-locate-python` was finding `/bin/python3` on the remote, which was not using an environment with `jupyter` installed.
