### ISSUE TITLE
tramp error: recursive load if use eshell/sudo

### ISSUE THREAD

**Issue by junyi-hou** [dzop/emacs-jupyter#172]
when installed from elpa, `jupyter-tramp` prevent users from using `eshell/sudo`

config file:

```
(require 'package)

(setq-default package-archives
              '(("org" . "http://orgmode.org/elpa/")
                ("melpa" . "http://melpa.org/packages/")
                ("elpy" . "https://jorgenschaefer.github.io/packages/")
                ("gnu" . "https://elpa.gnu.org/packages/")))

(setq package-enable-at-startup nil)
(package-initialize)

(require 'eshell)
(require 'em-tramp)
(add-to-list 'eshell-modules-list #'eshell-tramp)
```

enter `eshell-mode` and run `eshell/sudo ls`, error:
```
Recursive load: "/home/junyi/.emacs.d/elpa/jupyter-20190814.50/jupyter-tramp.el", "/home/junyi/.emacs.d/elpa/jupyter-20190814.50/jupyter-tramp.el", "/home/junyi/.emacs.d/elpa/jupyter-20190814.50/jupyter-tramp.el", "/home/junyi/.emacs.d/elpa/jupyter-20190814.50/jupyter-tramp.el", "/home/junyi/.emacs.d/elpa/jupyter-20190814.50/jupyter-tramp.el"
```

however, if one runs `eshell/su` first, `eshell/sudo` is back to normal.

**Comment by dzop** [comment]
Does `eshell/sudo` do anything special with files that end in `-tramp.el`? `jupyter-tramp` is not loaded anywhere in the code, i.e. there is no `(require 'jupyter-tramp)` anywhere. All the functions from `jupyter-tramp.el` being used are all auto-loaded.

Can you `toggle-debug-on-error` and show the backtrace when you get the `Recursive load` error.

**Comment by junyi-hou** [comment]
I agree that it is strange in the sense I did not even load `jupyter-tramp.el`. After more diggings, it seems like this is not an issue of `eshell/sudo` or `em-tramp`. Use this init file
```
(require 'package)

(setq-default package-archives
              '(("org" . "http://orgmode.org/elpa/")
                ("melpa" . "http://melpa.org/packages/")
                ("elpy" . "https://jorgenschaefer.github.io/packages/")
                ("gnu" . "https://elpa.gnu.org/packages/")))

(setq package-enable-at-startup nil)
(package-initialize)

(require 'eshell)
```

and run
```
(let ((default-directory "/sudo:root@localhost:/"))
    (eshell-named-command "ls"))
```
in an `eshell` buffer also leads to the recursive load problem.

I tried to turn on `debug-on-error` but there is no backtrace when I run both versions of the code.

**Comment by dzop** [comment]
Try putting

```emacs-lisp
(backtrace)
(signal 'quit nil)
```

at the top of the `jupyter-tramp.el` file and do your reproduction. Show the backtrace you get when doing this so we can see how the file is being loaded. Be sure to delete or recompile the `jupyter-tramp.elc` file after making the change and before attempting to reproduce the error.

**Comment by junyi-hou** [comment]
that's strange - after I delete `jupyter-tramp.elc` the problem goes away. Maybe something wired when I complie the package?

**Comment by dzop** [comment]
Very odd. It very well could have to do with stale `elc` files. Is the problem still gone after you recompile with `byte-compile-file`?

**Comment by dzop** [comment]
Closing since this seems to have to do with stale `elc` files.

**Comment by junyi-hou** [comment]
Sorry for the super-late reply. I have encountered the same problem again. Deleting `.elc` file or putting
```
(backtrace)
(signal 'quit nil)
```
at the beginning of `jupyter-tramp.el` did not help this time. I ran the command in `lisp-interaction-mode` and the error is now
```
tramp-find-foreign-file-name-handler: Recursive load: "/home/junyi/.emacs.d/straight/build/jupyter/jupyter-tramp.elc", "/home/junyi/.emacs.d/straight/build/jupyter/jupyter-tramp.elc", "/home/junyi/.emacs.d/straight/build/jupyter/jupyter-tramp.elc", "/home/junyi/.emacs.d/straight/build/jupyter/jupyter-tramp.elc", "/home/junyi/.emacs.d/straight/build/jupyter/jupyter-tramp.elc", "/usr/share/emacs/27.0.50/lisp/emacs-lisp/debug.elc"
```
which indicates it has something to do with `tramp-find-foreign-file-name-handler`?

**Comment by dzop** [comment]
TRAMP hijacks the normal `signal` mechanism to just produce messages instead of backtraces. Can you temporarily set `tramp-debug-on-error` to `t` and try to see if you can get a backtrace.

**Comment by junyi-hou** [comment]
Thanks for the quick response! I'll investigate tonight

**Comment by junyi-hou** [comment]
I tried to set `tramp-debug-on-error` to `t` but I could not get any backtrace. Just the same recursive load message. However, this problem goes away if I use the following minimal config
```
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(defun eshell/sudo (&rest args)
    "Use Tramp to re-implement sudo."
    (interactive)
    (throw
     'eshell-external
     (let* ((dir (file-local-name (expand-file-name default-directory)))
            (default-directory (concat "/sudo:root@localhost:" dir))
            (args (eshell-flatten-list args))
            (tramp-debug-on-error t))
       (eshell-named-command (car args) (cdr args)))))
(setq tramp-histfile-override "/dev/null")

(dolist (x (cl-remove-if-not (lambda (x) (not (equal (substring x 0 1) "."))) (directory-files "/home/junyi/.emacs.d/straight/build/")))
  (add-to-list 'load-path (concat "/home/junyi/.emacs.d/straight/build/" x)))

(require 'jupyter)
```

The cause of the problem is likely my config. I'll investigate more when I have time. Feel free to close this issue.

**Comment by junyi-hou** [comment]
I followed your earilier advice and added
```
(backtrace)
(signal 'quit nil)
```
at the top of `jupyter-tramp.el` then recompile the package. As before, no backtrace information is given and there's only the same old `Recursive load` info when I run anything under the `eshell` mode. But when I try to use `sudo-edit` which is a package that prefixes the current file with `/sudo:root@localhost:` and reopens it (so I can edit the file with sudo) outside of the eshell mode, it did give me the following backtrace:
```
  backtrace()
  byte-code("\300 \210\301\302\303\"\210\304\305!\210\304\306!\210\304\307!\210\304\310!\210\311\312\303\313\314\315%\207" [backtrace signal quit nil require jupyter-rest-api jupyter-server tramp tramp-cache custom-declare-group jupyter-tramp "TRAMP integration with the Jupyter Contents REST A..." :group jupyter] 6)
  jupyter-tramp-file-name-p("/sudo:root@localhost:/home/junyi/.emacs.d/site-lis...")
  tramp-find-foreign-file-name-handler("/sudo:root@localhost:/home/junyi/.emacs.d/site-lis..." expand-file-name)
  tramp-file-name-handler(expand-file-name "/sudo:root@localhost:/home/junyi/.emacs.d/site-lis..." nil)
  expand-file-name("/sudo:root@localhost:/home/junyi/.emacs.d/site-lis...")
  find-file-noselect("/sudo:root@localhost:/home/junyi/.emacs.d/site-lis..." nil nil nil)
  find-alternate-file("/sudo:root@localhost:/home/junyi/.emacs.d/site-lis...")
  sudo-edit(nil)
  funcall-interactively(sudo-edit nil)
  call-interactively(sudo-edit record nil)
  command-execute(sudo-edit record)
  execute-extended-command(nil "sudo-edit" #("sudo-edit\nsudo-edit\nsudo-edit-indicator-mode" 9 10 (read-only nil) 10 18 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ((:foreground "#ffffc8") ivy-current-match ivy-minibuffer-match-face-2)) 18 19 (read-only nil face ((:foreground "#ffffc8") ivy-current-match) help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 19 20 (read-only nil) 20 28 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 28 44 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight)))
  funcall-interactively(execute-extended-command nil "sudo-edit" #("sudo-edit\nsudo-edit\nsudo-edit-indicator-mode" 9 10 (read-only nil) 10 18 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ((:foreground "#ffffc8") ivy-current-match ivy-minibuffer-match-face-2)) 18 19 (read-only nil face ((:foreground "#ffffc8") ivy-current-match) help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight) 19 20 (read-only nil) 20 28 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight face ivy-minibuffer-match-face-2) 28 44 (read-only nil help-echo (format (if tooltip-mode "mouse-1: %s\nmouse-3: %s" "mouse-1: %s   mouse-3: %s") ivy-mouse-1-tooltip ivy-mouse-3-tooltip) mouse-face ivy-minibuffer-match-highlight)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

Quit
```
So it seems to me that `jupyter-tramp-file-name-p` is the root cause of this. If I run `juypter-tramp-file-name-p` manually before using any `sudo` command everything works fine, but if I did not run this before using `sudo`, I will get a recusrive load error.

Hope this helps.

**Comment by dzop** [comment]
@junyi-hou Thanks for the analysis. It gives me a good starting point for digging into it further.

**Comment by dzop** [comment]
I found the origin of the recursive load cycle thanks to the reproduction given by @zed in #215 

```
tramp-find-foreign-file-name-handler("/ssh:sshbox.example.com:/root/" expand-file-name)
tramp-file-name-handler(expand-file-name "/home/nathan/projects/elisp/jupyter/" "/ssh:sshbox.example.com:/root/")
file-name-case-insensitive-p("/home/nathan/projects/elisp/jupyter/")
file-truename("/home/nathan/projects/elisp/jupyter/jupyter-tramp.elc")
jupyter-tramp-file-name-p("/ssh:sshbox.example.com:/root/")
funcall(jupyter-tramp-file-name-p "/ssh:sshbox.example.com:/root/")
tramp-find-foreign-file-name-handler("/ssh:sshbox.example.com:/root/" expand-file-name)
```

It looks like what is happening is that, since `jupyter-tramp-file-name-p` is an autoload, the first call to the function will call `(load "/.../jupyter/jupyter-tramp")` and then call the real `jupyter-tramp-file-name-p`. I believe the call to `file-truename` originates from that call to `load` since its not called by anything inside `jupyter-tramp-file-name-p`.

In the call to `load`, but before `jupyter-tramp` is actually loaded, Emacs ends up calling `tramp-find-foreign-file-name-handler` again, thus the cycle.

Then I found the answer, https://github.com/emacs-mirror/emacs/blob/adcf904b3a7f8c5b8a82a40725ef7baa3a76c993/lisp/net/tramp-smb.el#L319-L325.

So the solution is to change `jupyter-tramp-file-name-p` to be a `defsubst` so that the whole function definition gets put in the autoload file.

**Comment by monnier** [comment]
@dzop: The backtrace above suggests that Emacs's `expand-file-name` will call the file-handler of the `default-directory` even if the first argument is already an absolute file name.  Maybe this can be useful in some unusual circumstance, but maybe it should be considered as a bug.

I suggest you file a bug report about it.

**Comment by junyi-hou** [comment]
Sorry for the late reply. I can confirm that this bug has been fixed.
