### ISSUE TITLE
No inline image display 

### ISSUE THREAD

**Issue by iwrotesomecode** [dzop/emacs-jupyter#178]
Hello, I'm unable to get images to display inline. I can get text output evaluated fine, but images are always displayed as follows.
```python
#+begin_src jupyter-python :session py
import numpy as np
import pandas as pd
x = np.linspace(1,100, 10)
y = np.random.normal(size=10)*x
df = pd.DataFrame({'x':x, 'y':y})
df.plot(x='x', y='y')
#+end_src

#+RESULTS:
:RESULTS:
: <matplotlib.axes._subplots.AxesSubplot at 0x7f30022619d0>
[[file:./.ob-jupyter/2846d2db35e9904ffd80731f93c7b53440fb6092.png]]
:END:
```
I've tried adding `  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images 'append)` to my config file, as well as `#+STARTUP: inlineimages` at the start of the org file. I've additionally tried toggling inline images with `C-c C-x C-v`. The later just toggles whether the file path is a link or not. 

Adding the header argument `:display image` results in ```Warning (emacs): Requested mimetype(s) not returned by kernel: (:image/png)```

**Comment by dzop** [comment]
Do inline images not produced by `emacs-jupyter` work? If they do, is the file `./.ob-jupyter/2846d2db35e9904ffd80731f93c7b53440fb6092.png` actually being written, i.e. does 
`(file-exists-p "./.ob-jupyter/2846d2db35e9904ffd80731f93c7b53440fb6092.png")` return non-nil?

Don't worry about the header argument thing, it's because

`: <matplotlib.axes._subplots.AxesSubplot at 0x7f30022619d0>`

and

`[[file:./.ob-jupyter/2846d2db35e9904ffd80731f93c7b53440fb6092.png]]`

come in from the kernel as two different messages. The first one doesn't have an `:image/png` mimetype. Its a bit confusing and I haven't really found the best way to fix it, ideas welcome. See https://github.com/dzop/emacs-jupyter/issues/144#issuecomment-517413879 for more details.

**Comment by iwrotesomecode** [comment]
If I evaluate the same src block with just python, it opens a pop-up with the plot. Inline does not work there either. It seems another issue is at play (emacs 26.2, fresh install of doom-emacs). I know that goes beyond the scope of emacs-jupyter, but any pointers welcome.

I tried evaluating whether the .ob-jupyter png was being written just in case, and `(file-exists-p "./.ob-jupyter/2846d2db35e9904ffd80731f93c7b53440fb6092.png")` returns nil. But if I toggle inline images and actually click on the link, I can see the plot in a new buffer.

**Comment by dzop** [comment]
Maybe try setting `org-image-actual-width` to `t` or `nil` if its not already, `org` tries to resize the image when that variable is not `t` or `nil` and uses imagemagick to do so, so it may have to do with how imagmagick is installed on your system.

**Comment by UndeadKernel** [comment]
It seems that I'm experiencing a similar problem. I cannot pinpoint if it's a problem with org, an external program or emacs-jupyter.
If the variable `org-image-actual-width` is set to `nil` or `t`, images are not displayed inline. If the variable is set to a number (e.g., 300) or a list of numbers (e.g., '(300)), inline images are displayed correctly.

**Comment by dzop** [comment]
All `emacs-jupyter` does is write the image to file and insert the image link (possibly with an `#+ATTR_ORG` line above it if `org-image-actual-width` is a list) so I suspect this is not an issue with `emacs-jupyter`.

**Comment by iwrotesomecode** [comment]
@UndeadKernel I am experiencing the same behavior. This provides a workaround to display inline images for me at least. Thanks!

**Comment by UndeadKernel** [comment]
In the Doom emacs issue tracker, we found that a recent change in `org-mode` broke displaying inline images if emacs is built in with `imagemagick`. [This commit](https://github.com/hlissner/doom-emacs/commit/87b7a8da052601c51bc0577484916856364401cb) in Doom emacs fixed the issue of inline images not being displayed.
