### ISSUE TITLE
missing cursor in REPL

### ISSUE THREAD

**Issue by dcherian** [dzop/emacs-jupyter#179]
I frequently lose the REPL cursor. It requires killing the buffer and opening a new kernel to bring it back. I think it might have something to do with errors being raised but I'm not sure. Do you have any suggestions on how to debug it?

**Comment by dzop** [comment]
Do you use an Emacs starter kit of some kind or `evil`? There is no code that messes with the cursor so I'm not sure how this could happen in the REPL. I would say check the value of `cursor-type` whenever its missing.
