### ISSUE TITLE
Cannot bind keys for jupyter-repl-mode

### ISSUE THREAD

**Issue by mankoff** [dzop/emacs-jupyter#180]
I'm having trouble binding `C-n` and `C-p` to `jupyter-repl-history-next` and `jupyter-repl-history-previous`, respectively, in the repl mode.

I see that these used to be defaults but were removed in in  9d685b0  as per #100, and in #90 someone else is having trouble and solves this. But their solution appears specific to `evil-mode` which I am not using.

It isn't clear to my why standard `use-package` syntax is not working here. I have tried:

```
(use-package jupyter
  :bind (:map jupyter-repl-mode-map
	      ("C-n" . jupyter-repl-history-next)
	      ("C-p" . jupyter-repl-history-previous)))
```

And elswhere, `(add-hook 'jupyter-repl-mode-hook (bind-key "C-n" #'jupyter-repl-history-next jupyter-repl-mode-map))`

But none of these seem to work.

**Comment by mankoff** [comment]
As for #100, `C-n` and `C-p` are commonly used for moving the point, but not exclusively. In repl mode and specifically with `comint mode`, they are often used to navigate history.

**Comment by dzop** [comment]
What does that `use-package` statement expand into, i.e. what does the following show? I don't use `use-package` myself.

```emacs-lisp
(cl-prettyprint
  (macroexpand
   `(use-package jupyter
      :bind (:map jupyter-repl-mode-map
                  ("C-n" . jupyter-repl-history-next)
                  ("C-p" . jupyter-repl-history-previous)))))
```

> `(add-hook 'jupyter-repl-mode-hook (bind-key "C-n" #'jupyter-repl-history-next jupyter-repl-mode-map))`

Did you mean `(lambda () (bind-key "C-n" #'jupyter-repl-history-next jupyter-repl-mode-map))`?

**Comment by mankoff** [comment]
> ```emacs-lisp
> (cl-prettyprint
>   (macroexpand
>    `(use-package jupyter
>       :bind (:map jupyter-repl-mode-map
>                   ("C-n" . jupyter-repl-history-next)
>                   ("C-p" . jupyter-repl-history-previous)))))
> ```

Evals to

```elisp
(progn
  (use-package-ensure-elpa 'jupyter '(t) 'nil)
  (defvar use-package--warning34
    (function
     (lambda (keyword err)
       (let ((msg (format "%s/%s: %s"
			  'jupyter
			  keyword
			  (error-message-string err))))
	 (display-warning 'use-package msg :error)))))
  (condition-case-unless-debug err
      (progn
	(unless (fboundp 'jupyter-repl-history-next)
	  (autoload (function jupyter-repl-history-next) "jupyter" nil t))
	(unless (fboundp 'jupyter-repl-history-previous)
	  (autoload (function jupyter-repl-history-previous) "jupyter" nil t))
	(bind-keys :package
		    jupyter
		    :map
		     jupyter-repl-mode-map
		     ("C-n" . jupyter-repl-history-next)
		     ("C-p" . jupyter-repl-history-previous)))
    (error (funcall use-package--warning34 :catch err))))
```

**Comment by mankoff** [comment]
> Did you mean `(lambda () (bind-key "C-n" #'jupyter-repl-history-next jupyter-repl-mode-map))`?

Yes! That solves it. Thank you.
