### ISSUE TITLE
Question/Discussion: How does this package fit with the rest of the emacs ecosystem if you want to have a python "IDE-like" configuration?

### ISSUE THREAD

**Issue by chm-gh** [dzop/emacs-jupyter#181]
First of all, I realize that the question raised in this issue may be too off-topic so feel free to close it at any moment if you feel that way.

Let me give you some insight into my current situation/usecases: I need to use ipython/jupyter for data science, so I tried both EIN and this package. I was particularly impressed by how emacs-jupyter communicates with the underlying kernel, enabling me to use an elisp-like workflow (evaluating stuff directly in the buffers I'm working on, instead of having to directly use the repl). I have not used it in conjunction with org-mode yet, but I certainly will in the future.

My point is that this package is extremely valuable to me, and I don't see myself replacing it with anything else in the future. Moving on forwards though, and starting using python extensively, I also would like to add many "IDE like" features(syntax checking, auto-formatting, documentation browsing) to my emacs configuration. My first effort in achieving that, by using elpy, was a complete failure since I didn't manage to make it synergize with emacs-jupyter in any way.

I wonder if you have any advice/suggestions for me going forwards: 
Is it possible to make emacs-jupyter work seamlessly with any of the "multipurpose" emacs packages for python like elpy/jedi/(something else?)? Is it instead preferable to avoid those and start using only those single-purpose packages that provide me with the functionality I want to have in addition to features of emacs-jupyter?

PS: Thank you for the excellent software

**Comment by dangom** [comment]
You can use lsp mode for IDE like features when working with python files. You can also use anaconda-eldoc-mode for eldoc support.

**Comment by chm-gh** [comment]
Correct me if I'm wrong, but given this advice I conclude that I will have to mix and match pieces from various other packages to get what I want and that there isn't any "one-stop" solution (like what I assume elpy/jedi has as its goal) that can be combined with emacs-jupyter.

If there isn't anything else to add to this discussion, please close this issue.

**Comment by dzop** [comment]
I think once more progress has been made on https://github.com/jupyter/enhancement-proposals/pull/26, we will see if there can be some kind of integration between `emacs-jupyter` and packages like `eglot` or `lsp-mode` which offer those IDE like features. Most likely there will be.

I think the best bet right now if you want to have IDE like features is to use one of `eglot` or `lsp-mode` in combination with `emacs-jupyter` for code evaluation.
