### ISSUE TITLE
Symbol’s function definition is void: jupyter-tramp-file-name-p

### ISSUE THREAD

**Issue by dangirsh** [dzop/emacs-jupyter#187]
I have an org subtree with the following property:

```
:PROPERTIES:
:header-args:jupyter-julia: :session /ssh:user@host:session-name
:END:
```

When I evaluate a `jupyter-julia` code block in this subtree, it fails with:

```
Symbol’s function definition is void: jupyter-tramp-file-name-p
```

The workaround is to manually evaluate the following forms:

In `jupyter-server.el`:

``` emacs-lisp
(declare-function jupyter-tramp-file-name-p "jupyter-tramp" (filename))
```

In `jupyter-tramp.el`:

``` emacs-lisp
;;;###autoload
(defsubst jupyter-tramp-file-name-method-p (method)
  "Return METHOD if it corresponds to a Jupyter filename method or nil."
  (and (string-match-p "\\`jpys?\\'" method) method))

;;;###autoload
(defun jupyter-tramp-file-name-p (filename)
  "If FILENAME is a Jupyter filename, return its method otherwise nil."
  (when (tramp-tramp-file-p filename)
    (jupyter-tramp-file-name-method-p
     (tramp-file-name-method (tramp-dissect-file-name filename)))))
```

Some of these evals might be unnecessary, but this is what worked for me just now.

This is a regression for me - the same org file with `emacs-jupyter` commit `f5499c6` worked without this issue.

I'm now on `emacs-jupyter` commit `53da538` using Emacs 27.0.50

**Comment by dzop** [comment]
Do you install `emacs-jupyter` manually? If the install happens through `package.el` or similar an autoload file should have been created and loaded which would avoid such problems.

**Comment by dangirsh** [comment]
Semi-manual. I point a spacemacs layer to a local git repo:

```
(setq my-jupyter-packages
      '(
        (jupyter :location local)
        ...
        ))

(defun my-jupyter/init-jupyter ()
  (use-package jupyter
    :init
    (setq jupyter-eval-use-overlays t)
    ))
```

with the `emacs-jupyter` source in `.../my-jupyter/local/jupyter`.

This has been my method for having development packages in Spacemacs, and I haven't had issues with other packages. If anyone knows a better way of setting up packages for development (in Spacemacs), I'd love to hear it?

I'm unfamiliar with how the autoload system works. I just tried `(package-generate-autoloads "jupyter" ".../my-jupyter/local/jupyter")`, which successfully generated a `jupyter-autoloads.el`, but didn't change anything.

I'll move to an official package for now, thanks.

**Comment by dzop** [comment]
You'll also want to call `(load "../jupyter-autoloads.el")` after generating the autoloads.

The autoload mechanism is just a way to defer loading of a file until a function it contains is actually called. For example, the autoload cookie, `;;;###autoload`, above `jupyter-tramp-file-name-p` in `jupyter-tramp.el` tells Emacs, after generating and loading the autoload file, to load `jupyter-tramp.el` if it isn't already on the first call to `jupyter-tramp-file-name-p`. See `C-h f autoload RET` for the details.

**Comment by dangirsh** [comment]
Great, thanks for the info.
