### ISSUE TITLE
Odd Point Movement With `jupyter-repl-echo-eval-p`

### ISSUE THREAD

**Issue by kevinjfoley** [dzop/emacs-jupyter#189]
When running `jupyter-repl-eval-line-or-region` with `jupyter-repl-echo-eval-p` set to `t` and the REPL buffer visible, I'm getting odd point movement.

It looks like `jupyter-with-repl-buffer` is setting the point properly but something else is setting it to another point.  Here's a recording of what I'm talking about - [demo](https://imgur.com/a/mEyosUK)

**Comment by fleimgruber** [comment]
I can't reproduce and do not know what could be causing this in `emacs-jupyter`.

**Comment by dzop** [comment]
Can you try to reproduce using a fresh Emacs instance with just Jupyter installed so that we can rule out any bad interactions with other packages?

**Comment by kevinjfoley** [comment]
I'm no longer able to reproduce, it was likely something in my config.  I did updat from `c4dc513c52c57a6f67d3c25c09079365dd2b06f5` to `9e3c1633586982e278f072dfaaabd115fa4d19f7` in since opening this so there's a chance something changed between those two.
