### ISSUE TITLE
Possible to `jupyter-run-repl` remotely?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#190]
It's easy to connect to a remote REPL via org mode and the :session syntax. I was wondering whether it'd also be possible to connect to a remote REPL via `jupyter-run-repl`. If yes, how would one go about to do that?

Thanks again.

**Comment by dzop** [comment]
To connect to a remote REPL (via the connection file), you can use `jupyter-connect-repl`. That's what the org-mode blocks use under the hood when `:session` is a JSON file.

**Comment by dzop** [comment]
@dangom did you mean something else? Like transparently starting a kernel on the remote? This is already possible with `jupyter-run-repl`. If the `default-directory` is a remote directory, `jupyter-run-repl` will start a kernel on the remote host using the `jupyter kernel` command on the remote.

**Comment by dangom** [comment]
This is amazing, I didn't know that! Works perfectly.

What (I think) I had in mind when I opened the issue was running `jupyter-run-repl` and having a drop down menu with both local kernels and previously used remote kernels. So far I'd been using org blocks to start remote kernels and then associating other buffers to it.

Please feel free to close this issue.
