### ISSUE TITLE
Unable to start python kernel

### ISSUE THREAD

**Issue by TMueller83** [dzop/emacs-jupyter#194]
Hi, I am not a jupyter expert, therefore sorry if the following issue is in fact due to my jupyter/python setup and not due to `emacs-jupyter`. However, if I try to run the org-mode example provided in the Readme:
```python
#+BEGIN_SRC jupyter-python :session py
x = 'foo'
y = 'bar'
x + ' ' + y
#+END_SRC
```
my minibuffer displays `Starting python3 kernel process...` for some seconds and then exits with the message
```
Kernel process exited:
/usr/bin/python: No module named ipykernel_launcher

Process jupyter-kernel-python3 exited abnormally with code 1
```
In the jupyter-notebook I can start python3 kernels without problems. I have tried to install the module `ipykernel_launcher` via `pip` however does not seem to be available.

Following the Readme I have put the following lines to my `.init` file in order to configure `emacs-jupyter`:
```
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (jupyter . t))
 )
```
**Some info:** I am using Emacs 26.3 which I have build from source by myself and org-mode 9.1.19. I have python 2.7.12 (=`python`), python 3.5.2 (=`python3`) and jupyter 4.4.0 installed in my system (Ubuntu 16.04).

**Comment by UndeadKernel** [comment]
Hey!
At least in Arch GNU/Linux, you want to install `python-ipykernel` to make `ipykernel_launcher` available to jupyter. Ubuntu must have a similar (if not the same) package in its repository.

**Comment by TMueller83** [comment]
Hi @UndeadKernel, thank you very much for your quick response! I could not find any `python-ipykernel` or similar package in the official Ubuntu repository. However, I have installed the `ipykernel` via pip by the command
```sh
sudo pip3 install ipykernel
```
I have done this already before I reported this issue. Does `emacs-jupyter` not work with a kernel installed via pip?

**Comment by UndeadKernel** [comment]
I don't know the answer to your question. We'll have to wait for @dzop.
`jupyter` doesn't have any problem working with `pip` packages (kernels), up to what I know.

**Comment by TMueller83** [comment]
Hey @UndeadKernel, no problem. Let's wait for him. Thanks a lot anyways for pointing out where to look for the problem!

**Comment by TMueller83** [comment]
Hi @dzop, thank you very much for your help! I think this line fixed my problem:
```
sudo python3 -m ipykernel.kernelspec
```
However, for completeness here is the requested output
```bash
$ which python
/usr/bin/python

$ which python3
/usr/bin/python3
``` 
and `(jupyter-locate-python)` returns `"/usr/bin/python3"`.

Now after I have installed the jupyter kernelspeck Emacs reports:
```
Starting python3 kernel process...done
```
so the python kernel seems to start correctly now. But now there comes another problem immediate afterwards:
```
defconst: Symbol’s value as variable is void: zmq-REQ
``` 
However, `zmq` has been installed in my Emacs as `emacs-jupyter` dependency (`zmq 20190812.1910`).

**Comment by dzop** [comment]
Since you are on Ubuntu you may be running into a bug with how Emacs was compiled on your system. What is your version of Ubuntu and gcc?

The version of Emacs on Ubuntu 16.04 is compiled with gcc 5.4.0 which has a bug in it that causes the error you've shown. See https://github.com/dzop/emacs-jupyter/issues/22#issuecomment-488113556 and comments afterwards for a solution and the details of the problem. Essentially you will want to get your hands on an Emacs built using gcc >= 6 or clang.

**Comment by TMueller83** [comment]
Hey @dzop, thank you very much for pointing this out! I am running Ubuntu 16.04 and yes you are right: I have gcc 5.4.0 installed and my Emacs has been compiled with this version of gcc. I will check out the solution in your link. Thanks again!
