### ISSUE TITLE
How to open a repl connected to the same session as my org SRC cells? 

### ISSUE THREAD

**Issue by MasonProtter** [dzop/emacs-jupyter#20]
Right now, it seems that when opening a REPL I can either associate it with a new session or provide a connection file to associate it with an existing session. I don't know how to find the connection file for the session associate with my org notebook cells. 

When opening a new REPL it'd be great if it provided a list of active kernels that I could connect to.

**Comment by non-Jedi** [comment]
Easiest way, and the way org-mode is designed for is to use `org-babel-switch-to-session`. Does this not work for your usecase for some reason?

**Comment by MasonProtter** [comment]
Oh I had no idea about `org-babel-switch-to-session`. Thanks!
