### ISSUE TITLE
Incomplete venv path

### ISSUE THREAD

**Issue by hankail05** [dzop/emacs-jupyter#200]
Thanks for the great package. It is what I want for jupyter-emacs integration.
However, when I activate venv with
``` emacs-lisp
(setq-local venv-location (file-name-directory buffer-file-name))
(venv-workon "venv")
```
emacs-jupyter kernel doesn't recognize venv path, but ipython from eshell does.
![Screenshot_20191115_111949](https://user-images.githubusercontent.com/39765074/68912144-9a1a6300-079a-11ea-935b-ae022de8f698.png)
My emacs-jupyter config is 
``` emacs-lisp
(leaf jupyter
  :ensure t
  :after org)
```
and virtualenvwarpper is
``` emacs-lisp
(leaf virtualenvwrapper
  :ensure t
  :config (progn (venv-initialize-interactive-shells)
                 (venv-initialize-eshell)))
```

**Comment by fleimgruber** [comment]
I was using a similar approach for conda environments initially. By now I have moved to using jupyter kernelspecs. You can list kernelspecs that `emacs-jupyter` knows about via `jupyter-available-kernelspecs`. For IPython, see the instructions e.g. [here](https://ipython.readthedocs.io/en/stable/install/kernel_install.html). Then when you do e.g. `jupyter-run-repl` you can select one of the kernels.

**Comment by hankail05** [comment]
![Screenshot_20191115_220949](https://user-images.githubusercontent.com/39765074/68945854-bc40cf00-07f4-11ea-8a41-ce3f7cb6890c.png)
Works well. Thanks!
