### ISSUE TITLE
[question] how to view graphical outputs under jupyter REPL?

### ISSUE THREAD

**Issue by randomizedthinking** [dzop/emacs-jupyter#202]
I use emacs-jupyter for python codes, and it works out greatly. One item that I would like to improve is to view graphical outputs properly. Below is a screenshot example: the plot is created, yet I don't know how to view it.

![image](https://user-images.githubusercontent.com/5283430/69763831-4e18d800-1123-11ea-8cb1-7c9bbc8beec6.png)

Yes, I can use org-mode and it can display inline image. Yet many times, I prefer to write code just in pure python. My question is that how I can view these graphical output then?

**Comment by dangom** [comment]
Could you paste your code instead of a screenshot? That would help others who want to help you.

**Comment by randomizedthinking** [comment]
Thanks, @dangom. Here is the code used in the above example:

``` python
import pandas as pd
from plotnine import ggplot, aes, geom_point, theme_bw, xlab, ylab, ggtitle

midwest = pd.read_csv("http://goo.gl/G1K41K")
midwest = midwest[midwest.poptotal < 50000]

ggplot(
    aes(x="area", y="poptotal", color="state", size="popdensity"), data=midwest
) + geom_point() + theme_bw() + xlab("Area") + ylab("Population") + ggtitle(
    "Area vs Population"
)
```

Also, I found if we set `(setq jupyter-repl-echo-eval-p t)`, then the code will be pasted in REPL and the image will be shown there.

**Comment by randomizedthinking** [comment]
I noticed that the plot is shown in another buffer named `*jupyter-display*`. Yet the buffer is blank, I have to scroll the buffer up and down, then the plot will show. Maybe something to do with the emacs configuration framework I use.

I will consider the issue resolved. Thanks.

**Comment by dangom** [comment]
I think the plot is just too large for the buffer, and Emacs doesn't smooth scroll images, so it just goes to a newline. That's why you have to scroll up
