### ISSUE TITLE
julia-latexsubs

### ISSUE THREAD

**Issue by linwaytin** [dzop/emacs-jupyter#205]
I'm trying ob-jupyter.
It shows an error as follows.

```elisp
executing Jupyter-Julia code block...
error in process sentinel: async-handle-result: Cannot open load file: No such file or directory, ~/Work/TDGL/src/v0.6/julia-latexsubs
error in process sentinel: Cannot open load file: No such file or directory, ~/Work/TDGL/src/v0.6/julia-latexsubs
```
`julia-latexsubs` should be a file in `julia-mode`, and I do have that package.
Not sure why jupyter tries to find it in my working directory.

**Comment by fleimgruber** [comment]
The file [julia-mode-latexsubs.el](https://github.com/JuliaEditorSupport/julia-emacs/blob/master/julia-mode-latexsubs.el) should indeed be in the `julia-mode` directory. Which versions of `julia-mode` and `emacs-jupyter` are you using and how do you load them?

**Comment by linwaytin** [comment]
`julia-mode` is 20191207
`emacs-jupyter` is 20191019
I load them using `use-package`.

**Comment by fleimgruber** [comment]
Could you try to debug `org-babel-execute:jupyter` in `ob-jupyter.el` with `edebug-defun`?

**Comment by dzop** [comment]
`emacs-jupyter` doesn't use the `async` package so the line

```elisp
error in process sentinel: async-handle-result: Cannot open load file: No such file or directory, ~/Work/TDGL/src/v0.6/julia-latexsubs
```

makes me think you also use `ob-async`. Is that the case? If so, does the suggestion [here](https://github.com/dzop/emacs-jupyter#integration-with-ob-async)  help? If not or if the suggestion doesn't help, can you show us the source block you are evaluating and that gives the error.

**Comment by linwaytin** [comment]
Sorry I haven't found time to deal with this issue until now.
I do have `ob-async` installed, but I forget if I added `:async` before.
Anyway, I just did a little test with the [suggestion](https://github.com/dzop/emacs-jupyter#integration-with-ob-async).
I didn't see the error message and the package works fine. 
Thank you!
