### ISSUE TITLE
Running org-mode code blocks on remote machine

### ISSUE THREAD

**Issue by SebastianCallh** [dzop/emacs-jupyter#216]
Hi! I tried this package out and I have to say it's really great. I got it running without any problem on the first attempt. I eventually tried to run org-mode code blocks on a remote machine, but I got stuck. I read the README about how you can use the `:session` parameter, but I'm not sure this applies to me. (However, all honesty didn't grok all of it).

In short, I have a remote machine running a dockerized Jupyter server. How do I execute my org-code blocks on this server? I think what I'm conceptually searching for is something like `jupyter-connect-server-repl` but for org-mode sessions.

**Comment by dzop** [comment]
Suppose you want to create a new Python kernel and have the session be
named `py`.

- `M-x jupyter-server-list-kernels` to display a list of live kernels on the server
- `C-RET` to launch a new Python kernel
- `R` to name the kernel session `py`, see `jupyter-server-kernel-names` for more
  info on kernel names.

Then assuming the notebook server is at http://localhost:8888 you would connect
to the session like so

```
#+begin_src jupyter-python :session /jpy:localhost#8888:py
...
#+end_src
```

See
https://github.com/dzop/emacs-jupyter/blob/master/README.org#communicating-with-kernel-notebook-servers and
https://github.com/dzop/emacs-jupyter/blob/master/README.org#tramp-integration
although the documentation does need some work.

Let me know if you meant something else or if I can clarify anything in the README.

**Comment by SebastianCallh** [comment]
Hi! 

I'm sorry for not getting back to you. The code block you proposed does indeed work!
