### ISSUE TITLE
Set Background color for images in REPL

### ISSUE THREAD

**Issue by arthurcgusmao** [dzop/emacs-jupyter#217]
![image](https://user-images.githubusercontent.com/12454729/74796279-63d40e80-52c8-11ea-89ba-de9b1f1cbb5e.png)
As shown in the image, the figure generated by `matplotlib.pyplot` is transparent with black text around it. Is there a way to define a default background color for the REPL's face for plots (or images, in general)? Being able to set the background of that line (or segment) to white would do it for me.

**Comment by dzop** [comment]
This has to do with the settings in `matplotlib`. You can change get your desired result with something like

```python
p  = plt.plot(se)
plt.gcf().patch.set_facecolor('#ffffff')
p
```

See https://matplotlib.org/3.1.3/tutorials/introductory/customizing.html and related. I'm not sure what the setting is to do it globally instead of on a per plot basis.

**Comment by arthurcgusmao** [comment]
Thank you @dzop !

After your solution I realized a default face color for a figure can be set using the matplotlibrc file, so a default solution can be to append to the `~/.config/matplotlib/matplotlibrc` file the following:
```
figure.facecolor: white
```

**References**
1. https://matplotlib.org/3.2.0/users/dflt_style_changes.html#patch-edges-and-color
2. https://www.scivision.dev/matplotlib-default-settings-matplotlibrc-where-is-it/
