### ISSUE TITLE
Multiline cells

### ISSUE THREAD

**Issue by jkroes** [dzop/emacs-jupyter#224]
RET executes the current cell, and I can't find a way to insert a newline for multiline cells.

**Comment by dzop** [comment]
You could try evaluating `(setq-default jupyter-repl-use-builtin-is-complete t)` and pressing RET in the cell and you should get a newline. In this case you have to press RET twice to send the cell to the kernel.

If the above works for you, then the problem may lie in the kernel you are using. What kernel are you using?

**Comment by jkroes** [comment]
I'll give this a try once work starts up again. I have Emacs set up there but not my personal computer, so it may be awhile before I can test this.
