### ISSUE TITLE
MELPA recipe

### ISSUE THREAD

**Issue by conao3** [dzop/emacs-jupyter#225]
Ref: https://github.com/melpa/melpa/pull/6009#pullrequestreview-371947271

I found your package bundle `Makefile` in MELPA package build. Do this file need by user?

**Comment by dzop** [comment]
Unfortunately the `Makefile` is needed by some users. I have an optional [feature](https://github.com/dzop/emacs-jupyter#building-the-widget-support-experimental) that requires building JavaScript using `node`.

A Makefile really isn't necessary for the build though, it is simple enough to be done with `compile` or similar (see https://github.com/dzop/emacs-jupyter/blob/master/js/Makefile).

**Comment by conao3** [comment]
OK, I see.
