### ISSUE TITLE
How to export entire file to ipynb?

### ISSUE THREAD

**Issue by chrisalcantara** [dzop/emacs-jupyter#232]
I'm having trouble finding in the documentation how exactly to export an `org` file, filled with iPython cells, to a `.ipynb` file that can be sent around. How can I do that?

**Comment by lccambiaghi** [comment]
Hi @chrisalcantara I use https://github.com/jkitchin/ox-ipynb, it works really well!

**Comment by dzop** [comment]
I also recommend using `ox-ipynb`, there isn't a way to do the conversion with this package.
