### ISSUE TITLE
Location of kernel session for org mode

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#24]
I have an org session evaluated, e.g., 
`#+BEGIN_SRC 
jupy-python :session py :kernel py36
#+END_SRC`

and I'd like to connect a jupyter REPL to it with `jupyter-connect-repl`, but the connection file is not stored in the standard place, e.g., on Linux, `/run/user/1001/jupyter/<file-name>.json`

Where is the session connection file stored from org mode? Or can I connect to the kernel in a different way?

**Comment by dzop** [comment]
Is this the same issue as in #20? You can just do `M-x org-babel-switch-to-session` when `point` is on a src-block.

**Comment by prittjam** [comment]
Yes. That works and is amazing. Thanks again!
