### ISSUE TITLE
jupyter-R stopped working

### ISSUE THREAD

**Issue by lccambiaghi** [dzop/emacs-jupyter#241]
Hi, I am using your excellent package through Doom Emacs. Everything worked perfectly until a recent update, where I lost the ability of using jupyter-R source code blocks. 

I don't really know how to help you reproduce it.. jupyter-python blocks are working as expected but for R I get `No org-babel-execute function for jupyter-R!` How can I help you troubleshoot it?

**Comment by dzop** [comment]
If you are getting that error for jupyter-R while jupyter-python works, maybe an R kernelspec couldn't be found on your system. The org-babel-execute function for a language is defined only if a kernelspec for the language can be found on your system. You can do `M-: (org-babel-jupyter-aliases-from-kernelspecs 'refresh)` and then try again to see if that helps. If it doesn't, does an R kernelspec show up when you run 
`jupyter kernelspec list` at a command line?

**Comment by lccambiaghi** [comment]
No luck even after refreshing. I can list the R kernelspec correctly:
```
Available kernels:
  ir         /Users/luca/Library/Jupyter/kernels/ir
  python3    /Users/luca/git/experiments/.venv/share/jupyter/kernels/python3
```

**Comment by dzop** [comment]
Can you show the output of 

```
(cl-prettyprint (jupyter-available-kernelspecs))
```

**Comment by lccambiaghi** [comment]
```
(("ir" "/Users/luca/Library/Jupyter/kernels/ir"
  :argv
   ["/Library/Frameworks/R.framework/Resources/bin/R" "--slave" "-e" "IRkernel::main()" "--args" "{connection_file}"]
   :env
    nil
    :display_name
     "R"
     :language
      "R"
      :interrupt_mode
       "signal"
       :metadata
        nil)
 ("python3" "/Users/luca/git/experiments/.venv/share/jupyter/kernels/python3"
  :argv
   ["python" "-m" "ipykernel_launcher" "-f" "{connection_file}"]
   :env
    nil
    :display_name
     "Python 3"
     :language
      "python"
      :interrupt_mode
       "signal"
       :metadata
        nil))
```

**Comment by lccambiaghi** [comment]
If it can help you, I can describe function `org-babel-execute:jupyter-python` but not `org-babel-execute:jupyter-R`. There is `org-babel-execute:jupyter-r` (lowercase) though.

**Comment by dzop** [comment]
Ahhh, I see what happened.  Thanks, the lowercase thing made me realize it. It has to do with the function `jupyter-canonicalize-language-string`, introduced in 308a4779d8f8dae8d261cac6c121a109aa911ad8.

For rigt now you can remove the `downcase` call in that function and then run `org-babel-jupyter-aliases-from-kernelspecs` again and everything should work again.

The `downcase` is not necessary, really just wanted to remove spaces from kernel language names since they would make using the `jupyter-lang` method specializer ugly in some cases, (see `cl-defmethod`), e.g. one would have to write `(jupyter-lang Wolfram\ Language)` instead of something like `(jupyter-lang Wolfram-Language)`.

**Comment by lccambiaghi** [comment]
Unfortunately that did not help.. I still see the function with the lowercase even after refreshing.

**Comment by lccambiaghi** [comment]
Oh I am sorry, it actually did fix it! I just needed to run `doom sync`. Thank you very much for you help and your amazing work, it has really improved my workflow!

**Comment by dzop** [comment]
Great, and your welcome!

**Comment by afermg** [comment]
I think I have a similar problem. When running either jupyter-python or jupyter-julia source blocks I get the same error.

`#+begin_src jupyter-julia :session test :exports results
2+2
#+end_src
`

I can't describe `org-babel-execute:jupyter-lang`, but I can do it for elisp and some others.

If I run
```
#+begin_src jupyter :kernel julia :session test :exports results
2+2
#+end_src

```
Then everything works fine, I can run the previous block and it starts a new session.

This is the output before running the :kernel block
```
(cl-prettyprint (jupyter-available-kernelspecs))
Output:
(("julia-1.0" "/home/user/.local/share/jupyter/kernels/julia-1.0"
  :argv
   ["/opt/julia-1.0.4/bin/julia" "-i" "--startup-file=yes" "--color=yes" "--project=@." "/home/user/.julia/packages/IJulia/gI2uA/src/kernel.jl" "{connection_file}"]
   :env
    nil
    :display_name
     "Julia 1.0.4"
     :language
      "julia"
      :interrupt_mode
       "signal"
       :metadata
        nil)
 ("python3" "/home/user/anaconda3/share/jupyter/kernels/python3"
  :argv
   ["/home/user/anaconda3/bin/python" "-m" "ipykernel_launcher" "-f" "{connection_file}"]
   :env
    nil
    :display_name
     "Python 3"
     :language
      "python"
      :interrupt_mode
       "signal"
       :metadata
        nil))

```

I'm using Ubuntu 20.04, Emacs 26.3 (doom-emacs), Org 9.4, and Jupyter 0.8.2-dev.

Anythin else that could be useful for debugging? 

Thanks heaps!

**Comment by afermg** [comment]
Nevermind, I hadn't noticed that I can directly add jupyter in init.el

If anyone has a problem like that, just change the org line ti (org +jupyter)
