### ISSUE TITLE
Color scheme in jupyter-repl makes text difficult to read, where can it be adjusted?

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#25]
Screenshot attached:

![screenshot from 2019-02-09 19-37-22](https://user-images.githubusercontent.com/1127761/52528085-9ce3a700-2ca2-11e9-806a-8d5c490bae13.png)

**Comment by dzop** [comment]
`M-x customize-face RET jupyter-repl-traceback RET` to change it.

Other faces are `jupyter-repl-input-prompt` and `jupyter-repl-output-prompt`.

**Comment by prittjam** [comment]
great, it is readable again!
