### ISSUE TITLE
emacs-jupyter and multiple conda environments - need help switching environment.

### ISSUE THREAD

**Issue by mankoff** [dzop/emacs-jupyter#253]
In the past I had one `conda` environment. In my `.bash_profile` I had a `conda activate foo`, and then `emacs-jupyter` worked just fine. Now I'm trying to have multiple conda environments, one per project. I am unable to switch which environment emacs-jupyter uses.

Having a per-project python (conda) environment also means, potentially, not have a conda environment active when I launch emacs. This is because the initial emacs launch is for Org Mode, mu4e, etc. and only later do I work on a project via `emacsclient`. **Note**: I realize a python environment with jupyter may be a requirement for `emacs-jupyter`, so I am not focusing on this here, but do raise the issue in #251. 

So, I have a base conda environment (`conda activate base` is in my ~/.bash_profile), and when I run Emacs and eval the following

````elisp
(shell-command-to-string "jupyter kernelspec list")
````

I get ```python3    /home/kdm/local/miniconda3/share/jupyter/kernels/python3```

I've configured `org`, `emacs-jupyter`, and `conda`, like this:

```elisp
(use-package org
  :ensure org-plus-contrib
  :config
  (setq org-confirm-babel-evaluate nil)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (shell . t)
     (octave . t)
     (jupyter . t))))

(use-package jupyter
  :init 
  (add-hook 'org-mode-hook (lambda () (jupyter-org-interaction-mode))))

(use-package conda
  :commands (conda-env-activate)
  :init
  (setq conda-anaconda-home "/home/kdm/local/miniconda3/")
  (conda-env-autoactivate-mode t))
```

To test changing environments, I have a folder `~/tmp/bar/`, a conda environment named `bar`, and `environments.yml` containing:

```yml
name: bar
dependencies:
  - numpy
  - pandas
  - jupyter
```

And when I `(find-file ~/tmp/bar/bar.org)` and eval  `(shell-command-to-string "jupyter kernelspec list")` I see `/home/kdm/local/miniconda3/envs/bar/share/jupyter/kernels/python3` which is the `bar` environment. Perfect! Except when I eval Python code, it reports the base environment:

```org
#+BEGIN_SRC jupyter-python :session debug 
import sys
print(sys.prefix)
#+END_SRC

#+RESULTS:
: /home/kdm/local/miniconda3
```
There is mention here: https://github.com/dzop/emacs-jupyter/issues/93#issuecomment-513603554 of the code `(add-hook 'pyvenv-post-activate-hooks (lambda() (jupyter-available-kernelspecs t)))` fixing this issue, but that does not work for me as-is (I'm not using pyvenv), nor if I try to change it to work with `conda`. 

I'm posting this here because according to `conda-env-activate`, the `bar` environment is active. I think that `emacs-jupyter` is not finding this environment.

**Comment by dangom** [comment]
I don't know how many environments you maintain, but if it's just a few, why not installing them as jupyter kernels instead of switching environments with `conda`?

See [this guide](https://janakiev.com/blog/jupyter-virtual-envs/).
I do this all the time to connect to different remote environments using the `:session` and `:kernel` options of org blocks.

**Comment by mankoff** [comment]
I wasn't aware of this feature of jupyter. Thank you for sharing.

I was not able to solve the issue above using the emacs `conda` package, but was able to with `pyvenv`:

```emacs-lisp
(use-package pyvenv
  :init
  (pyvenv-mode 1)
  (pyvenv-tracking-mode 1)
  (add-hook 'pyvenv-post-activate-hooks (lambda() (jupyter-available-kernelspecs t)))
)
```

With the key line being the `add-hook`, which refreshes the jupyter kernel list for each environment (because they aren't sharing them in user space). In order to automate this I use `.dir-locals.el` with, for example, `((nil . ((eval . (pyvenv-workon "some_env")))))`. Everything seemed to work.

With your suggestion. I can remove `pyvenv` from my emacs init, and remove the `.dir-locals.el` files scattered around folders (invisible actors - not great for my confused future self), and instead just add `:kernel some_env` to the `jupyter-python` babel blocks. This is cleaner. Thank you.

Any advice how to select a default kernel? If I don't specify `:kernel` then it appears to default to the first one, alphabetic order, from `jupyter kernelspec list`.

**Comment by dangom** [comment]
I have the following in my init:

```
(use-feature ob
  :demand t
  :after (:all jupyter python)
  :config
  ;; Set better default settings for org-babel.
  (setf (alist-get :async org-babel-default-header-args:jupyter-python) "yes")
  (setf (alist-get :kernel org-babel-default-header-args:jupyter-python) "python3")
  (setf (alist-get :session org-babel-default-header-args:jupyter-python) "py3")
  ;; Julia not setup yet and not loaded in org-babel-do-load-languages.
  ;; (setf (alist-get :async org-babel-default-header-args:jupyter-julia) "yes")
  )
```

**Comment by mankoff** [comment]
Yes, I solved it with:

```
(setq org-babel-default-header-args:jupyter-python
      (cons '(:kernel . "base")
	    (assq-delete-all :kernel org-babel-default-header-args)))
```

when I load `Org`.

I still have to have a base environment active when I launch emacs which I would prefer not to have (see #251), but overall things work well now. Thank you!

I'm going to close this as this works and the `pyvenv` method works, and I'm sure someone with better lisp skills than I could get the `conda` emacs package to update the jupyter kernel list too.
