### ISSUE TITLE
rebind jupyter-eval-line-or-region in org interaction mode from =C-x C-e= to =gb= (evil mode)

### ISSUE THREAD

**Issue by adder** [dzop/emacs-jupyter#263]
Hey
I evaluate often single lines and regions in org src block in jupyter-org-interaction-mode.
This is don with jupyter-eval-line-or-region and is currently bound to =C-x C-e=.
However, as an evil user (doom emacs), I would like a more pinky friendly keybinding :)
Executing src blocks (org-ctrl-c-ctrl-c) are currently bound to =gr= in normal mode.
Likewise I would like to bind jupyter-eval-line-or-region to =gb=.

However, I am not able to get it to work.
anybody a clue?

**Comment by lccambiaghi** [comment]
Hey, what a coincidence, I just performed this exact binding:
```
(map! :after jupyter
      :map python-mode-map
      :localleader
      (:desc "eval" :prefix "e"
       :desc "line or region" :n "e" #'jupyter-eval-line-or-region
       :desc "buffer" :n "b" #'jupyter-eval-buffer))
```

This should work for your case:
```
(map! :after jupyter
      :map python-mode-map
       :desc "eval line or region" :n "gr" #'jupyter-eval-line-or-region)
```

**Comment by adder** [comment]
Thanks a lot!
