### ISSUE TITLE
jupyter-output and jupyter-error windows not reused

### ISSUE THREAD

**Issue by sebastianpech** [dzop/emacs-jupyter#27]
I find the following behavior quite strange, is it intended?

Starting from one window showing a buffer with source code.
When I run a line which causes an error, the current window
is split below (half) and the buffer jupyter-error is
displayed there.
When I then run a line which produces output, the source code window is
split again and the buffer jupyter-output is displayed.
So far so good.
However, when I now run a line which again causes an error the code
window is split again displaying the jupyter-error buffer in two different
windows.
This way alternating output and error creates a bunch of vertically
stacked windows, until the code window reaches a certain height at which
point the window below of the code window is reused. 

This also happens with multiple columns (see screenshot).
I think having one dedicated buffer for output and error would really help unclutter the frame.

![image](https://user-images.githubusercontent.com/13043943/52593139-86775000-2e48-11e9-9ad7-8666e9f8244b.png)

**Comment by dzop** [comment]
No, this is not intended. I believe it has to do with how `display-buffer` is used in those cases. I guess I never noticed this behavior since I use https://github.com/bmag/emacs-purpose for managing my windows.

**Comment by sebastianpech** [comment]
When I noticed the behavior is reactivated my purpose config but purpose was completely ignored. Very strange that it's working for you ...

**Comment by dzop** [comment]
OK, no your right. It doesn't work for me either. When I did error, output, error I still had only one error and one output, but continuing more start popping up.

**Comment by dzop** [comment]
Should work now.

**Comment by sebastianpech** [comment]
Yes it's working, thanks. However, it's still somehow interfering with purpose and I can't dedicate a window to show all the `jupyter-*` buffers.

**Comment by dzop** [comment]
Try replacing

```
(append '(display-buffer-reuse-window)
            actions
            '(display-buffer-pop-up-window))
```

with 

```
'(display-buffer-reuse-window)
```

in `jupyter-display-current-buffer-reuse-window`. It could be the pop-up window function that is causing the issue.

**Comment by sebastianpech** [comment]
Now I can't tell if purpose is working or not because the window is always reused ;). I'll look into it, but this seems to be a purpose related problem

**Comment by dzop** [comment]
Can you try replacing the definition of `jupyter-display-current-buffer-reuse-window` with 

```emacs-lisp
(let ((display-buffer-base-action
         (cons
          (append '(display-buffer-reuse-window)
                  actions
                  '(display-buffer-pop-up-window))
          (cl-list*
           '(pop-up-windows . t)
           alist))))
    (display-buffer (current-buffer)))
```

I was able to get this working with a purpose config of

```emacs-lisp
(purpose-set-extension-configuration
 :jupyter (purpose-conf :regexp-purposes '(("\\*jupyter-*" . jupyter))))
```

**Comment by sebastianpech** [comment]
With this everything works as expected. When not dedicated two separate windows are viewed for error and output and they are reused accordingly. When those two have the same purpose and the window is dedicated only one window is viewed and reused. 

Thanks for the quick response, are you planning to  commit the [above](https://github.com/dzop/emacs-jupyter/issues/27#issuecomment-462647386) code for `jupyter-display-current-buffer-reuse-window`?

**Comment by dzop** [comment]
Yes.
