### ISSUE TITLE
interacting with REPL after jupyter-connect-repl

### ISSUE THREAD

**Issue by lwoloszy** [dzop/emacs-jupyter#29]
Long time user of ob-ipython here... I just learned about your package and it looks like everything I hoped ob-ipython would some day become. Good stuff.
 
After connecting to an already existing kernel via `jupyter-connect-repl`, when I try to interact with the REPL, I'm getting a Kernel not alive message. Interestingly, sending blocks of code works, and I can inspect the variables by running a separate `jupyter console --existing` in a terminal window. Thoughts?

**Comment by dzop** [comment]
Thanks for catching this. It looks like I was forgetting to start the heartbeat channel. When using `jupyter-connect-repl` the heartbeat channel is relied on to determine if the kernel is alive. In contrast `jupyter-run-repl` just checks that the kernel process is alive. Does the latest master fix the issue?

**Comment by lwoloszy** [comment]
Perfect, thanks.
