### ISSUE TITLE
Error if /run/user/1000/jupyter doesn't exist yet

### ISSUE THREAD

**Issue by non-Jedi** [dzop/emacs-jupyter#3]
Installing this on another computer, I ran into a problem after invoking `jupyter-run-repl` where it was clear that emacs-jupyter was trying to create a file in `/run/user/1000/jupyter` but such a directory didn't yet exist as I hadn't previously used jupyter on this system. Problem was fixed by simply running `jupyter console` once.

**Comment by non-Jedi** [comment]
@dzop if you're interested in accepting PRs for this package, I might take a stab at fixing this one myself as it seems likely to be relatively simple and a good way to dip my toes into the codebase. I foresee this package becoming a very important part of my workflow, so I *would* like to learn enough to give back a bit if possible.

**Comment by dzop** [comment]
Yes PR's are welcome! And please keep the bug reports coming 👍.

**Comment by non-Jedi** [comment]
@dzop ftr, I still have this problem on commits after 7e42bdd. Haven't said anything because I've been meaning to try to fix myself, but I just haven't had time. Probably worth reopening issue.

**Comment by benneti** [comment]
Probably the simplest fix would be to add 
`(files--ensure-directory "/run/user/1000/jupyter")`
(always returns nil and creates the directory if it does not exist)
to `jupyter-start-new-kernel` eg. line 336 in the kernel manager file.
A quick test by deleting the folder and then using the kernel shows that it works.

**Comment by dzop** [comment]
@benneti `files--ensure-directory` is what `make-directory` uses internally already and `make-directory` is what is used in 7e42bdd80e1ff97b934d817fbaba6c0166b95b47 so I don't see how using `files--ensure-directory` would be any different than using `make-directory`.

Maybe it is that the `make-directory` call is not happening? But then the
`file-directory-p` call should have returned non-nil which would mean the directory already exists. This doesn't make much sense though.

**Comment by benneti** [comment]
I don't know wether this is helpful, but here is a traceback of the error

```
Debugger entered--Lisp error: (file-missing "Creating file with prefix" "No such file or directory" "/run/user/1000/jupyter/emacs-kernel-")
  make-temp-file-internal("/run/user/1000/jupyter/emacs-kernel-" nil ".json" nil)
  make-temp-file("emacs-kernel-" nil ".json")
  #f(compiled-function (manager &optional timeout) "Start a kernel and associate it with MANAGER.\n\nThe MANAGER's `name' property is passed to\n`jupyter-find-kernelspecs' in order to find the kernel to start.\nIf `jupyter-find-kernelspecs' returns multiple kernelspecs that\nmatch `name', the first one on the list is used.\n\nIf a valid kernel is found, its kernelspec is used to start a new\nkernel. Starting a kernel involves the following steps:\n\n1. Write the connection info of MANAGER's session to a file in\n   the `jupyter-runtime-directory'.\n\n2. Start a kernel subprocess passing the connection info file as\n   the {connection_file} argument in the kernelspec argument\n   vector of the kernel.\n\n3. Connect the control channel of MANAGER to the kernel." #<bytecode 0x2695ee9>)(#<jupyter-kernel-manager jupyter-kernel-manager>)
  apply(#f(compiled-function (manager &optional timeout) "Start a kernel and associate it with MANAGER.\n\nThe MANAGER's `name' property is passed to\n`jupyter-find-kernelspecs' in order to find the kernel to start.\nIf `jupyter-find-kernelspecs' returns multiple kernelspecs that\nmatch `name', the first one on the list is used.\n\nIf a valid kernel is found, its kernelspec is used to start a new\nkernel. Starting a kernel involves the following steps:\n\n1. Write the connection info of MANAGER's session to a file in\n   the `jupyter-runtime-directory'.\n\n2. Start a kernel subprocess passing the connection info file as\n   the {connection_file} argument in the kernelspec argument\n   vector of the kernel.\n\n3. Connect the control channel of MANAGER to the kernel." #<bytecode 0x2695ee9>) #<jupyter-kernel-manager jupyter-kernel-manager> nil)
  jupyter-start-kernel(#<jupyter-kernel-manager jupyter-kernel-manager>)
  jupyter-start-new-kernel("julia-1.0" jupyter-org-client)
  jupyter-run-repl("julia-1.0" nil nil jupyter-org-client)
  org-babel-jupyter-initiate-session-by-key("jl" ((:colname-names) (:rowname-names) (:result-params "replace" "drawer") (:result-type . value) (:results . "replace drawer") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:kernel . "julia-1.0") (:async . "no") (:session . "jl")))
  org-babel-jupyter-initiate-session("jl" ((:colname-names) (:rowname-names) (:result-params "replace" "drawer") (:result-type . value) (:results . "replace drawer") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:kernel . "julia-1.0") (:async . "no") (:session . "jl")))
  org-babel-execute:jupy-julia("using Plots" ((:colname-names) (:rowname-names) (:result-params "replace" "drawer") (:result-type . value) (:results . "replace drawer") (:exports . "code") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:kernel . "julia-1.0") (:async . "no") (:session . "jl")))
  org-babel-execute-src-block(nil ("jupy-julia" "using Plots" ((:colname-names) (:rowname-names) (:result-params "drawer" "replace") (:result-type . value) (:results . "drawer replace") (:exports . "code") (:session . "jl") (:async . "no") (:kernel . "julia-1.0") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no")) "" nil 158 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Also I think the make-directory call is not happening, because if I put.
I think the issue is with the position in code, because moving `make-directory` here:
```
  (unless (jupyter-kernel-alive-p manager)
    (cl-destructuring-bind (kernel-name . (resource-dir . spec))
        (car (jupyter-find-kernelspecs (oref manager name)))
      (unless (file-directory-p jupyter-runtime-directory) ;; this is line 187
        (make-directory jupyter-runtime-directory 'parents))
      (let* ((temporary-file-directory jupyter-runtime-directory)
      ...
```
fixes the problem.
Also if `make-directory` calls `files--ensure-directory` is the `(unless ...)` really necessary?

**Comment by dzop** [comment]
Oh I see the problem. Your supposed to create the directory before calling `make-temp-file` because it tries to guarantee that the file name it creates is unique which means it has to look at all the files in the directory that begin with the prefix provided. Whoops! 

And yes, the `unless` is unnecessary since the `parents` argument is non-nil in `make-directory`.
