### ISSUE TITLE
Ctrl-c Ctrl-c in elpy sends code to new REPL after associating buffer

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#30]
If I associate an open buffer with `M-x jupyter-repl-associate-buffer` and then `Crtl-C Ctrl-C` in that buffer and new python interpreter is started instead of sending code to the associated jupyter REPL.

**Comment by dzop** [comment]
What is the command shown when you press `C-h k C-c C-c`? It should be `jupyter-eval-line-or-region`.

I'm thinking there is some interference with keymaps, i.e. `elpy` binds `C-c C-c` in a keymap that takes precedence over the keymap that `jupyter-eval-line-or-region` is defined in.

Note, `jupyter-eval-line-or-region` is also bound to `C-x C-e`.

**Comment by prittjam** [comment]
C-c C-c runs the command elpy-shell-send-region-or-buffer (found in
elpy-mode-map), which is an interactive compiled Lisp function in
‘elpy-shell.el’.

It is bound to C-c C-c, C-c C-y r, <menu-bar> <Elpy> <Interactive
Python> <Send Region or Buffer>.

(elpy-shell-send-region-or-buffer &optional ARG)

Run ‘elpy-shell-send-region-or-buffer-and-step’ but retain point position.

[back]

is there a way to override this so that Crtl-c Ctrl-c send the command to the jupyter-repl, or perhaps unbind this?

**Comment by dzop** [comment]
You can unbind it with 

```
(define-key elpy-mode-map (kbd "C-c C-c") nil)
```

**Comment by prittjam** [comment]
perfect!
