### ISSUE TITLE
New emacs frame for traceback on error

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#34]
The current behavior opens a new window when an error occurs. Is it possible to set the default behavior to open a new frame with just the traceback as its content? This would allow the window layout for code editing and evaluation (REPL) to remain undisturbed.

**Comment by dzop** [comment]
It shouldn't be too difficult to add an option that controls whether a traceback is displayed in a frame or a window.

**Comment by prittjam** [comment]
ok, great and thanks. I thought that maybe there was a way to override that without a code fix.

**Comment by dzop** [comment]
OK you should be able to pop up frames by default with

```
(setq jupyter-pop-up-frame t)
```
