### ISSUE TITLE
Text results don't appear with :async yes

### ISSUE THREAD

**Issue by apnewberry** [dzop/emacs-jupyter#37]
When async is disabled, all results appear underneath. When async is enabled, images appear, but text results don't. In the first code block, text is produced, but no output appears until async is disabled. The image appears correctly despite async in the third block.

```python

#+BEGIN_SRC jupyter-python :session xx :kernel python3 :async yes :results drawer
x = 'foo'
y = 'bar'
print(x + ' ' + y)
#+END_SRC

#+RESULTS:
:results:
:end:


#+BEGIN_SRC jupyter-python :session xx :kernel python3 :async no :results drawer
x = 'foo'
y = 'bar'
print(x + ' ' + y)
#+END_SRC

#+RESULTS:
: foo bar
:


#+BEGIN_SRC jupyter-python :async yes
import time

import numpy as np
import matplotlib.pyplot as plt


time.sleep(3)
plt.hist(np.random.randn(20000), bins=200)
#+END_SRC

#+RESULTS:
[[file:./.ob-jupyter/cfc8c7633939dad5fe6075720e6bba41d2db9402.png]]

```

Ubuntu 18.04
Emacs 26.1
Python 3.6.5
emacs-jupyter "v0.7.2-15-gea5ae74"

**Comment by UndeadKernel** [comment]
I can replicate this error.
If I remove `:results drawer`, things are printed fine even with `:async yes`.

**Comment by dzop** [comment]
Thanks there was actually a bug here. It should work on the latest master. But in general, `:results drawer` doesn't need to be specified since the results will automatically be wrapped in a drawer if they need to be. Regardless, everything should work fine if you specify `:results drawer`.
