### ISSUE TITLE
org-mode: Alias for code block identifier

### ISSUE THREAD

**Issue by fleimgruber** [dzop/emacs-jupyter#41]
When users want to migrate from their existing org files which use

```
#+BEGIN_SRC python
1 + 1
#+END_SRC
```

to

```
#+BEGIN_SRC jupyter-python
1 + 1
#+END_SRC
```

the question arose whether it is possible to let org-mode know that a source block identifier `python`
 should really use the machinery of the identifier `jupyter-python` - so no changes to existing org files are necessary.
For major mode discrimination there is `org-src-lang-modes`, but is there a similar thing for choosing the eval backend?

**Comment by non-Jedi** [comment]
Here's a snippet from my config that does what you're asking for:

```elisp
  (with-eval-after-load 'ob-jupyter
    (defalias 'org-babel-execute:julia 'org-babel-execute:jupyter-julia)
    (defalias 'org-babel-julia-initiate-session
      'org-babel-jupyter-julia-initiate-session))
```

**Comment by fleimgruber** [comment]
Thanks for the snippet. I adapted it for Python and it works. We could put this into the README, @dzop what do you think?

**Comment by dzop** [comment]
Sounds like a good idea, but there are more aliases that would also be useful, e.g. to setup an `org-edit-src` buffer connected to the same session as the src-block.

What we can do is create a new function along the lines of `org-babel-jupyter-make-language-alias` and then give an example on how to use that function to override the default `org-mode` languages in the README. Note, all of the aliases in that function can be used except for `expand-body` and `variable-assignments`.
