### ISSUE TITLE
error: Channel not started in ioloop subprocess (:shell)

### ISSUE THREAD

**Issue by galeo** [dzop/emacs-jupyter#43]
Executing the `jupyter-run-repl` command will cause this error.

The backtrace log:
```
Debugger entered--Lisp error: (error "Channel not started in ioloop subprocess (:shell)")
  signal(error ("Channel not started in ioloop subprocess (:shell)"))
  error("Channel not started in ioloop subprocess (%s)" :shell)
  #f(compiled-function (client channel) "Verify that CLIENT's CHANNEL started.\nRaise an error if it did not start within\n`jupyter-default-timeout'." #<bytecode 0x4079f845>)(#<jupyter-repl-client jupyter-repl-client> :shell)
  apply(#f(compiled-function (client channel) "Verify that CLIENT's CHANNEL started.\nRaise an error if it did not start within\n`jupyter-default-timeout'." #<bytecode 0x4079f845>) (#<jupyter-repl-client jupyter-repl-client> :shell))
  #f(compiled-function (&rest args) #<bytecode 0x43fdc151>)(#<jupyter-repl-client jupyter-repl-client> :shell)
  apply(#f(compiled-function (&rest args) #<bytecode 0x43fdc151>) #<jupyter-repl-client jupyter-repl-client> :shell)
  jupyter-start-channel(#<jupyter-repl-client jupyter-repl-client> :shell)
  #f(compiled-function (arg1 &rest rest) "Start the pre-configured channels of CLIENT.\nBefore starting the channels, ensure that the channel subprocess\nresponsible for encoding/decoding messages and sending/receiving\nmessages to/from the kernel is running.\n\nCall `jupyter-start-channel' for every channel whose key has a\nnon-nil value passed to this function.\n\nIf the shell channel is started, send an initial\n`:kernel-info-request' to set the kernel-info slot of CLIENT if\nnecessary." #<bytecode 0x4079f90d>)(#<jupyter-repl-client jupyter-repl-client>)
  apply(#f(compiled-function (arg1 &rest rest) "Start the pre-configured channels of CLIENT.\nBefore starting the channels, ensure that the channel subprocess\nresponsible for encoding/decoding messages and sending/receiving\nmessages to/from the kernel is running.\n\nCall `jupyter-start-channel' for every channel whose key has a\nnon-nil value passed to this function.\n\nIf the shell channel is started, send an initial\n`:kernel-info-request' to set the kernel-info slot of CLIENT if\nnecessary." #<bytecode 0x4079f90d>) #<jupyter-repl-client jupyter-repl-client>)
  #f(compiled-function (&rest args) #<bytecode 0x404b14f1>)(#<jupyter-repl-client jupyter-repl-client>)
  apply(#f(compiled-function (&rest args) #<bytecode 0x404b14f1>) #<jupyter-repl-client jupyter-repl-client> nil)
  jupyter-start-channels(#<jupyter-repl-client jupyter-repl-client>)
  jupyter-start-new-kernel("python3" jupyter-repl-client)
  jupyter-run-repl("python3" nil t nil t)
  funcall-interactively(jupyter-run-repl "python3" nil t nil t)
  #<subr call-interactively>(jupyter-run-repl record nil)
  apply(#<subr call-interactively> jupyter-run-repl (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> jupyter-run-repl record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (jupyter-run-repl record nil))
  call-interactively(jupyter-run-repl record nil)
  command-execute(jupyter-run-repl record)
  execute-extended-command(nil "jupyter-run-repl")
```

**Comment by dzop** [comment]
Does that error consistently happen?

**Comment by galeo** [comment]
I have not succeeded in making it work.

I just installed this package from MELPA using the built-in package manager. During the installation process, it prompts to compile and install zmq and succeed.

Then executing the command `jupyter-run-repl` will cause this error.

`(shell-command "jupyter kenelspec list")` returns the available kernel "python3".

**Comment by dzop** [comment]
What is your

- OS
- Emacs version (`M-x emacs-version`)

You may be facing some issues with Emacs processes than anything related to Jupyter since this error only occurs when the Emacs subprocess responsible for communicating with the Jupyter channels does not respond within a timeout period.

Also, can you set `zmq--subprocess-debug` to `t` and `jupyter--debug` to `t`, try again, and show all of the messages you get in the `*Messages*` buffer.

**Comment by galeo** [comment]
OS: macOS Majave 10.1.4.3
Emacs version: GNU Emacs 26.1.92 (build 2, x86_64-apple-darwin18.2.0, Carbon Version 158 AppKit 1671.2) of 2019-02-21 ([The Emacs Mac port](https://bitbucket.org/mituharu/emacs-mac/overview))

The log:
```
finalizer failed: (wrong-type-argument stringp nil)
START-CHANNEL: (:shell)
QUIT: nil
Entering debugger...
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-poller’
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-pre-hook’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-pre-hook’
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-timeout’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-poller’
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-session’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-post-hook’
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-post-hook’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-nsockets’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-timeout’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-socket-types’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-channels’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-session’
STDERR[zmq<1>]: Warning: assignment to free variable ‘jupyter-ioloop-channels’
STDERR[zmq<1>]: Warning: reference to free variable ‘cl-struct-jupyter-session-tags’
STDERR[zmq<1>]: Warning: reference to free variable ‘jupyter-ioloop-timers’
START: nil
```

**Comment by dzop** [comment]
Hmm...I'm on an identical OS but my Emacs version is

```
GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.0.0, Carbon Version 158 AppKit 1671) of 2019-02-11
```

I'm wondering if you can roll back your Emacs version and try again to see if it has to do with upstream changes in Emacs process handling?

**Comment by galeo** [comment]
My version of Emacs was build with the latest HEAD of [`work`](https://bitbucket.org/mituharu/emacs-mac/branch/work) branch. I will roll back the version and have a try. 

Thanks.

**Comment by dzop** [comment]
Obviously not a permanent solution, but it would be good to confirm if that is the cause.

**Comment by galeo** [comment]
The error still occurs after rolling back the version of Emacs.

However, executing the `jupyter-run-repl` command in Emacs terminal mode works fine. I also tried to open Emacs in GUI mode with the `-q` parameter, execute `package-initialize`, and then execute `jupyter-run-repl`, which will also succeed.

I am checking my Emacs configuration file and want to find out what caused this error.

**Comment by galeo** [comment]
Hi @dzop, I finally solved this problem by just increasing the value of `jupyter-default-timeout`. The value of `1` second may be too small. Should this value be set a bit larger by default?

**Comment by dzop** [comment]
It’s surprising that it would take more than 1 second to get a response from a sub-process though, it’s not like there is any network communication going on when that error occurs. I think it may have to do with the following line

https://github.com/dzop/emacs-jupyter/blob/a76e8d51512ad3d5858215e1ddf167a589f83ce3/jupyter-channel-ioloop.el#L189

Could you maybe reduce that to 0.1 and see if you still get that error.

Also since you were able to get it working in GUI mode without any packages, do you have a lot of timers or other sub processes that are running when in the GUI? If changing the above doesn’t work then it may also be that the output of the channel subprocess isn’t being processed fast enough.

**Comment by galeo** [comment]
Setting the value of `sleep-for` to `0.1` does not work.

Emacs has no other child processes except `aspell` and `server`.  And the timers list:
```
 Idle    Next     Repeat Function
           4.92     0.00 auto-revert-buffers
          24.48     1.00 ac-clear-variables-every-minute
   *       0.00        t #f(compiled-function () #<bytecode 0x400f12c9> [eldoc-mode global-eldoc-mode eldoc--supported-p eldoc-print-current-symbol-info])
   *       0.05     0.00 popwin:close-popup-window-timer
   *       0.10        t mouse-avoidance-fancy
   *       0.12        t show-paren-function
   *       0.50        t jit-lock-context-fontify
   *       0.50        t symbol-overlay-maybe-put-temp
   *       1.00        t amx-idle-update
   *       1.00        t which-key--update
   *       5.00        t color-identifiers:refresh
   *       5.00        t mac-cleanup-expired-apple-events
   *      30.00        - desktop-auto-save
   *      30.00        t js-gc
```

This may be due to the fact that the output of the channel subprocess is not getting fast enough.
