### ISSUE TITLE
"Modlues are not supported" - package load error

### ISSUE THREAD

**Issue by theottm** [dzop/emacs-jupyter#46]
Hello,

thanks a lot for this new projects, I can't wait to try it !

Unfortunately I ran quickly into a  wall... I get this error message when running (require 'jupyter) : 
`Modlues are not supported`

I didn't enabled widgets at emacs compilation, maybe that's the reason ?

**Comment by non-Jedi** [comment]
What version of emacs are you running? Modules weren't added until 25.

**Comment by theottm** [comment]
"GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2018-07-06"

**Comment by dzop** [comment]
Your Emacs needs to have been built using the `--with-modules` configure flag. If the value of the
`module-file-suffix` variable is `nil` then it wasn't. If you don't have module support, there is probably a way to get an Emacs with modules through whatever package manager you downloaded Emacs from. 

What Linux distribution do you have? Maybe someone will know how you can get an Emacs with modules support if they know the Linux distribution.

**Comment by theottm** [comment]
Ok I see. I'll try to change that config or reinstall. My distrib is Debian Stretch.

**Comment by theottm** [comment]
Apparently it is not going to be in the package release any soon : http://debian.2.n7.nabble.com/Bug-914568-emacs25-Please-build-with-xwidget-support-td4423323.html

I built it from source. And it works :)
