### ISSUE TITLE
Can't use the Org :dir keyword with top-level-only Julia expressions

### ISSUE THREAD

**Issue by dangirsh** [dzop/emacs-jupyter#57]
It seems like the implementation of `org-babel-jupyter-transform-code` in `jupyter-julia.el` doesn't work expressions like `using Foo`, as Julia complains that `using` can only be run at the top-level.

Example:

```
#+BEGIN_SRC jupyter-julia :dir ~/
using Plots
#+END_SRC

#+RESULTS:
:RESULTS:
# [goto error]
: syntax: "using" expression not at top level
: 
:END:
```

I'm using a Julia 1.0.3 kernel and emacs-jupyter commit ea5ae74.

**Comment by dzop** [comment]
Thanks, fixed on latest master.

**Comment by dangirsh** [comment]
The fix caused a new issue: top-level variables are now captured by the `let` block:

#+begin_src jupyter-julia
a = 1
#+end_src

#+RESULTS:
: 1

#+begin_src jupyter-julia
a
#+end_src

#+RESULTS:
:RESULTS:
# [goto error]
: UndefVarError: a not defined
:
: Stacktrace:
:  [1] top-level scope at ./In[2]:4
:END:

**Comment by dangirsh** [comment]
Ah, the `try` also captures bindings!

**Comment by dzop** [comment]
Yeah the let block wasn’t a good idea. But I will have to figure out how to preserve the directory in the case of an error.

**Comment by dzop** [comment]
OK, looks like I can use the [posterror_hook](https://github.com/JuliaLang/IJulia.jl/blob/bd9b39e27e0c41ebd8aa8d5d0a6ed5388924e439/src/IJulia.jl#L251) for this purpose.

**Comment by dzop** [comment]
Everything should be good to go.

**Comment by dangirsh** [comment]
Works, thanks!!
