### ISSUE TITLE
Trying to display a png slows emacs to crawl and spikes memory

### ISSUE THREAD

**Issue by non-Jedi** [dzop/emacs-jupyter#6]
I saw over 7 Gb of memory used with emacs constantly spinning at 100% on a cpu when trying to display a 150 Kb png before emacs was oom killed. Example reproduction:

```julia
using Pkg; Pkg.add("FileIO")
using FileIO
load("example.png")
```

**Comment by dzop** [comment]
Is your version of `emacs-jupyter` older than 172f29b4fe0a482130fdb273d52416d6f2a4368d? If so, it might have to do with what was printed to the REPL.

**Comment by non-Jedi** [comment]
I've pulled latest master and am failing to reproduce this now. Although the output I'm getting is plaintext rather than png like I had expected. Will do further digging.

**Comment by non-Jedi** [comment]
So I figured out that I had loaded `Images` previously before `FileIO`, which is what defines the `show` method for pngs for the loaded example.png, but I did that again just now, and everything worked beautifully without any problem, too, so I'm guessing this was a one-off thing or fixed by something on master.
