### ISSUE TITLE
jupyter-LANG-mode does not exist, causing issue with evilnc-comment-operator

### ISSUE THREAD

**Issue by benneti** [dzop/emacs-jupyter#68]
When using evils `comment-or-uncomment-region` region it tries to start `jupyter-julia-mode` and fails (as it doesn't exist) and equivalently for python.
The function does this as it looks for the `(org-element-property :language (org-element-at-point))` property to start the mode that controlls the commenting.

`(defalias 'jupyter-julia-mode 'julia-mode)`

makes it work but I feel like there is a cleaner way using
`(jupyter-kernel-language-mode ??)` in the alias, could you tell whether this works and how to call this function?
I wether this is an issue that should be fixed in emacs-jupyter or an incompatibility between this and evil comment.

But if there are more packages assuming one can start the mode with the `:language` property of the org element it might be good to create these aliases when creating the babel languages.

**Comment by dzop** [comment]
I believe the variable `org-src-lang-modes` is used to map languages to major modes. From the variable documentation

```
Alist mapping languages to their major mode.
```

We already add to this variable when doing the aliasing. 

Looking at the related function in `evil-nerd-commenter`

https://github.com/redguardtoo/evil-nerd-commenter/blob/d1a5c9cd63dcb8c22dc27d657926efb4b673a7f4/evil-nerd-commenter.el#L315

it looks like they should be using `org-src-lang-modes` for both cases, falling back to the `:language` key when there is no entry in `org-src-lang-modes`. So something like

```emacs-lisp
(setq lang
      (let ((lang (org-element-property :language (org-element-at-point))))
        (or (cdr (assoc lang org-src-lang-modes))
            lang)))
```

I don't use `evil-nerd-commenter` so feel free to use the above to submit a pull request to that project.

**Comment by benneti** [comment]
Thank you, you are awesome :+1:
