### ISSUE TITLE
Trouble switching buffers when persistent-mode active

### ISSUE THREAD

**Issue by poppyschmo** [dzop/emacs-jupyter#76]
First off, thanks for this package. Was hoping someone would make it happen, and you did it!

Specifically, `jupyter-repl-propagate-client`'s calls to `get-buffer` and `buffer-local-value` sometimes throw when `switch-to-buffer` is passed nonexistent/dead buffers/names (or nil).

Naive hackery makes this go away (no idea, though):
```patch
diff --git a/jupyter-repl.el b/jupyter-repl.el
index 770feac..be8e11e 100644
--- a/jupyter-repl.el
+++ b/jupyter-repl.el
@@ -1867,10 +1867,10 @@ NOTE: Only intended to be added as advice to `switch-to-buffer',
   (let* ((other-buffer (get-buffer
                         (if (or (null win-or-buffer)
                                 (windowp win-or-buffer))
-                            (car args)
+                            (or (car args) (other-buffer))
                           win-or-buffer)))
          (client
-          (and jupyter-current-client
+          (and other-buffer jupyter-current-client
                (object-of-class-p jupyter-current-client 'jupyter-repl-client)
                (eq (buffer-local-value 'major-mode other-buffer)
                    (jupyter-kernel-language-mode jupyter-current-client))

```
From `switch-to-buffer`'s docstring:

> BUFFER-OR-NAME may be a buffer, a string (a buffer name), or nil.
> ...
> If BUFFER-OR-NAME is nil, switch to the buffer returned by ‘other-buffer’.

May be able to conjure up an ERT scriptlet for reproducing in your Travis container if necessary.

**Comment by dzop** [comment]
Thanks I will look into a solution. This is a case of me trying to be too clever and have one function be used as advise for many different functions. I think we should break up `jupyter-repl-propagate-client` into a core function that does the actual work of setting the `jupyter-current-client` in the buffer being displayed/switched to and a few helper functions that handle the various argument cases for each function being advised.

**Comment by poppyschmo** [comment]
Breaking up the advice seems like the way to go. No rush, of course, and much appreciated.
