### ISSUE TITLE
Will R be supported?

### ISSUE THREAD

**Issue by tianshu-shuke** [dzop/emacs-jupyter#78]
Thanks for the awesome work!  

Python and julia have been supported in the package. Will R be added?

I'm not familiar with elisp. However, if R is not in the plan, I'd learn elisp and modify the jupyter-python.el for R.  😀

**Comment by dzop** [comment]
I don't use R, but will be willing to assist with anything if R doesn't already work out of the box. The jupyter-python.el kind of files are mainly used to work around any rough edges that may be present with a languages and to add in any language specific extra features.

**Comment by non-Jedi** [comment]
See also #87
