### ISSUE TITLE
Support displaying multiple returned images

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-jupyter#8]
How easy would it be to display multiple images returned by the kernel?
I could imagine that, for each image returned, a link to the image could be added just as it is being done with a single image.

Thank you for the amazing work you've done in this package @dzop.

**Comment by dzop** [comment]
Thanks for reporting this.

When you say "multiple images returned" are you referring to calling something like `IPython.display.display` (or `display` in IJulia) multiple times in the code block or returning a list of images from the code block? If its the latter, it can't be done on the Emacs side. You would still have to call some type of `display` function in the kernel.

The machinery is already setup to append the contents of `display_data` messages as they come in, but it currently doesn't work properly when appending file links. This has been a common source of problems but I think I have finally fixed the issue and will push changes soon.

**Comment by UndeadKernel** [comment]
I was referring to the case where multiple "file links" were appended to the results, I assume.
Take this as an example:

```python
#+BEGIN_SRC jupy-python :session plots :async yes
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

xs = np.linspace(0,100,100)
plt.plot(xs, xs*xs)
plt.show()

plt.plot(xs, np.sqrt(xs))
plt.show()
#+END_SRC
```
Notice that two `plot()` calls are made. Jupyter notebooks displays two images, one after the other.
Currently, `ob-jupyter` displays only a link to a file of the last plot.

**Comment by dzop** [comment]
Yes each `plt.show` call emits a `display_data` message so they both are handled, but when the second one comes in the first one is overwritten since currently there is an issue with appending multiple file links. I have a fix for this that I will push soon.

Also for future reference, the flow of messages sent to Emacs by the kernel can be printed to the `*Message*` buffer by setting the variable `jupyter--debug` to `t`.

**Comment by UndeadKernel** [comment]
Thanks for the explanation.
The variable `jupyter--debug` was a great idea.
