### ISSUE TITLE
Is the remote kernel functionality broken?

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-jupyter#86]
I cannot seem to get the remote kernel functionality to work.

In a remote server, to start jupyter notebooks, I issue the command:
```bash
jupyter notebook --no-browser
```
This creates a session file that looks like `/home/boy/.local/share/jupyter/runtime/nbserver-30692.json`.
This file contains these fields:
```json
{
  "url": "http://localhost:8888/",
  "pid": 30692,
  "secure": false,
  "base_url": "/",
  "port": 8888,
  "hostname": "localhost",
  "notebook_dir": "/home/boy"
}
```
In an org file I then specify the session
```
:session /ssh:entropyOs:/home/boy/.local/share/jupyter/runtime/nbserver-30692.json
```

Jupyter fails with the error message:
```
Format specifier doesn’t match argument type
```
given that in [this line](https://github.com/dzop/emacs-jupyter/blob/master/jupyter-client.el#L289) the parameters to the `format` function are all `nil`.

Am I doing things correctly or did something break?

**Comment by dzop** [comment]
See #81. The Jupyter notebook isn’t supported since the ZMQ sockets don’t get exposed. I’m trying to add in support for the Jupyter gateway (https://github.com/jupyter/kernel_gateway) which uses websockets for communication, which the notebook also uses, so hopefully support is coming soon.

**Comment by UndeadKernel** [comment]
Go it. Didn't realize it was the same error.
I guess the confusion comes from the instructions in the README that explain how to connect to a remote kernel. It'd probably be a good idea to specify how to run a kernel remotely so that the org client can be used. I now realize you need to manually start a kernel with `jupyter kernel --kernel=`, which was not obvious to me.
Also, is the syntax for specifying remote sessions correct in the README? I was first experimenting with session names like:
``
:session /entropyOs:/<dir>/kernel-30692.json
```
but then realize that it should instead probably be:
```
:session /ssh:entropyOs:/<dir>/kernel-30692.json
```
Notice that the second example has `ssh:` in it.

**Comment by dzop** [comment]
Since this issue has appeared twice, the README probably should be updated.

Yes your right about the session format, I think the `/entropyOs:` form was allowed in an older Emacs version.
