### ISSUE TITLE
Requirement of zeromq with draft API

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-jupyter#9]
Hey @dzop,

The library works very well. However, I faced many issues installing libzmq with draft API support. Most distributions do not supply the library with that compilation option enabled. In Arch GNU/Linux, for example, the package zeromq (which supplies libzmq) has to be recompiled from scratch and manually set to enable the draft APIs.

I was thinking that two paths could be taken to make this library easier to install for others:
1) Only use the non-draft API and detect if it's enabled for optional functionality.
2) Provide a static local library (of libzmq) and compile it at installation time.

Do you think any of those two are a possibility?

**Comment by UndeadKernel** [comment]
Sorry, I was supposed to post this issue in the dzop/emacs-zmq repository.
Should I repost it over there and close this one?

**Comment by dzop** [comment]
Yes I think that would be best.
