### ISSUE TITLE
Remapping keybinding to toggle the REPL history

### ISSUE THREAD

**Issue by hilman-dayo** [dzop/emacs-jupyter#90]
First of all, I want to say a big thank you for this package.
I am moving from `ob-ipython` to this package and am loving it!

However, I got a question.
I am a Emacs newbie and am using Spacemacs.
I want to define keybindings for the `jupyter-repl-mode` such that in the repl, I can press `C-j` and `C-n` to toggle the history (I am heavily influenced by the VIM keybinding).

I tried below code snippets with no success.
 

    (with-eval-after-load 'jupyter
      (define-key jupyter-repl-mode-map (kbd "C-k") 'jupyter-repl-history-previous)
      (define-key jupyter-repl-mode-map (kbd "C-j") 'jupyter-repl-history-next)
    )

I hope someone can direct me to the right direction in making this working.
Thanks.

**Comment by dzop** [comment]
I'm assuming your using `evil` since you are using Spacemacs and you mentioned VIM. If you are you will have to do something like

```emacs-lisp
(evil-define-key 'normal jupyter-repl-mode-map (kbd "C-k") 'jupyter-repl-history-previous)
(evil-define-key 'normal jupyter-repl-mode-map (kbd "C-j") 'jupyter-repl-history-next)
```

I don't use Spacemacs so maybe there is a more canonical way.

**Comment by hilman-dayo** [comment]
OK, go it working. Thank you! Now I can return to my work with a huge relief!

However, I do not understand why my previous method does not work. 
This is because I remapped a keybinding in org-mode like below and it is working.

    (define-key org-mode-map (kbd "C-m") 'org-return-indent)

**Comment by dzop** [comment]
It probably has to do with keymap precedence, see https://github.com/noctuid/evil-guide#keymap-precedence.

**Comment by hilman-dayo** [comment]
Got it. Thank you so much for the answer. It really helps an Emacs beginner like me!
