### ISSUE TITLE
Remote kernel does not respond to kernel-info request

### ISSUE THREAD

**Issue by r5h** [dzop/emacs-jupyter#94]
On a remote server, I start a jupyter console using 
```
jupyter console -f /home/user/connection.json
```
When I add a code block with a reference to the connection file like so
```
#+BEGIN_SRC jupyter-python :session /ssh:user@host:/home/user/connection.json
a = 1
#+END_SRC
```
I get the following messages
```
Tramp: Inserting ‘/ssh:user@host:/home/user/connection.json’...
Tramp: Encoding remote file ‘/ssh:user@host:/home/user/connection.json’ with ‘base64 <%s’...done
Tramp: Decoding local file ‘/tmp/tramp.Q2B4Nz.json’ with ‘base64-decode-region’...done
Tramp: Inserting ‘/ssh:user@host:/home/user/connection.json’...done
Requesting kernel info...done
jupyter-kernel-info: Kernel did not respond to kernel-info request
```

This also happens when I try to connect using `M-x jupyter-connect-repl` and specify the connection file.

The remote host is running jupyter console version `6.0.0`. I am running the current MELPA version of `emacs-jupyter`, which is `jupyter-20190310.939`.

Any idea as to what the cause may be?

**Comment by nanounanue** [comment]
See #61 

You need to fire a `jupyter-kernel` not a `jupyter console`

:)

**Comment by UndeadKernel** [comment]
We've all made that mistake @r5h :D (see #86)
What @nanounanue said is correct: you need to spawn a "raw" kernel rather than a "console" or a "notebook server".

**Comment by dzop** [comment]
@r5h Are you still having issues?

**Comment by r5h** [comment]
Sorry for the slow reply, but the issue is resolved. Thanks for the help!
