### ISSUE TITLE
Error on `save-buffers-kill-terminal`

### ISSUE THREAD

**Issue by r-zip** [dzop/emacs-jupyter#98]
First of all, thank you for all your hard work! This is the first sane approach I've seen to Jupyter integration in Emacs, and I've wanted this package for a very long time. Please let me know if I can contribute in some way (although my knowledge of elisp and common lisp are pretty minimal).

I'm having a problem quitting Emacs when I have a Jupyter process running. If I press <kbd>C-x C-c</kbd> to kill emacs while a REPL buffer is open, I get the following error message:
`list-processes--refresh: Wrong type argument: sequencep, t`

I would expect the REPL buffer close dialogs to be triggered instead of this mysterious error.

**Comment by dzop** [comment]
I'm glad that you are liking the package!

The issue is actually with the `list-processes--refresh` function itself. It doesn't appear to handle pipe processes that have a nil or t `process-command`. Below is a patch that fixes the issue. Although you will most likely have to re-define the function in your init file since,  if you modify simple.el directly, the change won't take effect after an Emacs restart unless you re-build Emacs.

```diff
---
 lisp/simple.el | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/lisp/simple.el b/lisp/simple.el
index 29bfc63716..304d3311b9 100644
--- a/lisp/simple.el
+++ b/lisp/simple.el
@@ -4016,7 +4016,8 @@ list-processes--refresh
 				     (if speed
 					 (format " at %s b/s" speed)
 				       "")))))
-		     (mapconcat 'identity (process-command p) " "))))
+                     (if (not (stringp (process-command p))) ""
+		       (mapconcat 'identity (process-command p) " ")))))
 	     (push (list p (vector name pid status buf-label tty cmd))
 		   tabulated-list-entries)))))
   (tabulated-list-init-header))
-- 
```

**Comment by rzpilgrim** [comment]
Thanks for the tip. If I just redefine the function in my init.el, then it doesn't seem to work. I get the following error: 
`cond: Symbol’s value as variable is void: main-thread`

Do I need to require `simple` or something to access that variable? I'm not sure how scoping works in elisp. I'm using Emacs 26.2, by the way.

**Comment by dzop** [comment]
Seems to be a new variable in Emacs 26.2, I'm still on 26.1. It should be available even if your Emacs was built without thread support according to its documentation

https://github.com/emacs-mirror/emacs/blob/a1386fa6a7698c04902354cd5fefb39056b0a901/doc/lispref/threads.texi#L134

The variable isn't defined in simple.el, it is defined on the C level

https://github.com/emacs-mirror/emacs/blob/6f3cf12e4fb6c810ebf37c8819dc2ee39b02199e/src/thread.c#L1124

**Comment by r-zip** [comment]
I haven't had much more time to debug this, but after switching to Mituharu's `emacs-mac` fork, I'm no longer having this problem.
