### ISSUE TITLE
Autocomplete in org-src buffers

### ISSUE THREAD

**Issue by rzpilgrim** [dzop/emacs-jupyter#99]
If I open an org-src buffer using <kbd>C-c '</kbd>, the autocompletion from the Jupyter process does not work. However, autocompletion in the org buffer works just fine. It would be nice to get consistent autocompletion in org-src buffers.

**Comment by dzop** [comment]
If `jupyter-repl-interaction-mode` is enabled in the org-src buffer then completion should work. You should see the function `jupyter-completion-at-point` in the `completion-at-point-functions` list when inside the org-src buffer. Even if `jupyter-completion-at-point` is in the list, another completion function may be preventing its use if it is not the first function in the list.

You can verify that `jupyter-repl-interaction-mode` is enabled in the org-src buffer by examining the enabled minor modes when calling `describe-mode` (`C-h m`), you should see `Jupyter-Repl-Interaction` in the enabled minor modes.

**Comment by rzpilgrim** [comment]
Thanks for your reply. Although it was first in `completion-at-point-functions`, it did not work. Disabling `anaconda-mode` through `org-src-mode-hook` seems to do the trick, though.

**Comment by Salompas** [comment]
@r-zip How did you get completion working in the first place? I inspected `completion-at-point-functions` but the only thing I have is `tags-completion-at-point-function`, and I cannot find `jupyter-completion-at-point` anywhere.

**Comment by r-zip** [comment]
@Salompas Sorry for the delay. I didn't see your comment for some reason. 

I'm not sure. Here's my jupyter configuration:

```emacs-lisp
(when (functionp 'module-load)
  (straight-use-package 'jupyter)
  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((jupyter . t))))
  (with-eval-after-load 'jupyter
    (define-key jupyter-repl-mode-map (kbd "C-l") #'jupyter-repl-clear-cells)
    (define-key jupyter-repl-mode-map (kbd "TAB") #'company-complete-common-or-cycle)
    (define-key jupyter-repl-interaction-mode-map (kbd "C-c C-r") #'jupyter-eval-line-or-region)
    (define-key jupyter-repl-interaction-mode-map (kbd "C-c M-r") #'jupyter-repl-restart-kernel)
    (define-key jupyter-repl-interaction-mode-map (kbd "C-c M-k") #'jupyter-shutdown-kernel)
    (add-hook 'jupyter-repl-mode-hook (lambda () (display-line-numbers-mode -1)))
    (add-hook 'jupyter-repl-mode-hook #'smartparens-mode)
    (setq jupyter-repl-prompt-margin-width 4)
```

Nothing out of the ordinary, it just works.
